// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mock_service.go -package=service github.com/rudderlabs/rudder-server/regulation-worker/internal/service
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	backendconfig "github.com/rudderlabs/rudder-server/backend-config"
	model "github.com/rudderlabs/rudder-server/regulation-worker/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAPIClient is a mock of APIClient interface.
type MockAPIClient struct {
	ctrl     *gomock.Controller
	recorder *MockAPIClientMockRecorder
	isgomock struct{}
}

// MockAPIClientMockRecorder is the mock recorder for MockAPIClient.
type MockAPIClientMockRecorder struct {
	mock *MockAPIClient
}

// NewMockAPIClient creates a new mock instance.
func NewMockAPIClient(ctrl *gomock.Controller) *MockAPIClient {
	mock := &MockAPIClient{ctrl: ctrl}
	mock.recorder = &MockAPIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIClient) EXPECT() *MockAPIClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockAPIClient) Get(ctx context.Context) (model.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx)
	ret0, _ := ret[0].(model.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAPIClientMockRecorder) Get(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAPIClient)(nil).Get), ctx)
}

// UpdateStatus mocks base method.
func (m *MockAPIClient) UpdateStatus(ctx context.Context, status model.JobStatus, jobID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, status, jobID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockAPIClientMockRecorder) UpdateStatus(ctx, status, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockAPIClient)(nil).UpdateStatus), ctx, status, jobID)
}

// Mockdest is a mock of dest interface.
type Mockdest struct {
	ctrl     *gomock.Controller
	recorder *MockdestMockRecorder
	isgomock struct{}
}

// MockdestMockRecorder is the mock recorder for Mockdest.
type MockdestMockRecorder struct {
	mock *Mockdest
}

// NewMockdest creates a new mock instance.
func NewMockdest(ctrl *gomock.Controller) *Mockdest {
	mock := &Mockdest{ctrl: ctrl}
	mock.recorder = &MockdestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockdest) EXPECT() *MockdestMockRecorder {
	return m.recorder
}

// GetDestination mocks base method.
func (m *Mockdest) GetDestination(destID string) (*backendconfig.DestinationT, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDestination", destID)
	ret0, _ := ret[0].(*backendconfig.DestinationT)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDestination indicates an expected call of GetDestination.
func (mr *MockdestMockRecorder) GetDestination(destID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDestination", reflect.TypeOf((*Mockdest)(nil).GetDestination), destID)
}

// Mockdeleter is a mock of deleter interface.
type Mockdeleter struct {
	ctrl     *gomock.Controller
	recorder *MockdeleterMockRecorder
	isgomock struct{}
}

// MockdeleterMockRecorder is the mock recorder for Mockdeleter.
type MockdeleterMockRecorder struct {
	mock *Mockdeleter
}

// NewMockdeleter creates a new mock instance.
func NewMockdeleter(ctrl *gomock.Controller) *Mockdeleter {
	mock := &Mockdeleter{ctrl: ctrl}
	mock.recorder = &MockdeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockdeleter) EXPECT() *MockdeleterMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *Mockdeleter) Delete(ctx context.Context, job model.Job, dest *backendconfig.DestinationT) model.JobStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, job, dest)
	ret0, _ := ret[0].(model.JobStatus)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockdeleterMockRecorder) Delete(ctx, job, dest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*Mockdeleter)(nil).Delete), ctx, job, dest)
}
