package logfield

const (
	UploadJobID                = "uploadJobID"
	UploadStatus               = "uploadStatus"
	UseRudderStorage           = "useRudderStorage"
	SourceID                   = "sourceID"
	SourceType                 = "sourceType"
	DestinationID              = "destinationID"
	DestinationType            = "destinationType"
	DestinationRevisionID      = "destinationRevisionID"
	DestinationValidationsStep = "step"
	WorkspaceID                = "workspaceID"
	Namespace                  = "namespace"
	Schema                     = "schema"
	Error                      = "error"
	TableName                  = "tableName"
	ColumnName                 = "columnName"
	ColumnType                 = "columnType"
	Priority                   = "priority"
	Retried                    = "retried"
	Attempt                    = "attempt"
	LoadFileType               = "loadFileType"
	LoadTableStrategy          = "loadTableStrategy"
	ErrorMapping               = "errorMapping"
	DestinationCredsValid      = "destinationCredsValid"
	Query                      = "query"
	QueryExecutionTime         = "queryExecutionTime"
	StagingTableName           = "stagingTableName"
	SampleDuplicateMessages    = "sampleDuplicateMessages"
)
