package logfield

const (
	UploadJobID                = "uploadJobID"
	UploadStatus               = "uploadStatus"
	UseRudderStorage           = "useRudderStorage"
	TaskRunID                  = "taskRunID"
	SourceID                   = "sourceID"
	SourceType                 = "sourceType"
	DestinationID              = "destinationID"
	DestinationType            = "destinationType"
	DestinationRevisionID      = "destinationRevisionID"
	DestinationValidationsStep = "step"
	WorkspaceID                = "workspaceID"
	Namespace                  = "namespace"
	Schema                     = "schema"
	Error                      = "error"
	Status                     = "status"
	ErrorCategory              = "errorCategory"
	TableName                  = "tableName"
	ColumnName                 = "columnName"
	ColumnType                 = "columnType"
	Priority                   = "priority"
	Retried                    = "retried"
	Attempt                    = "attempt"
	LoadFileType               = "loadFileType"
	ShouldMerge                = "shouldMerge"
	ErrorMapping               = "errorMapping"
	DestinationCredsValid      = "destinationCredsValid"
	Query                      = "query"
	QueryExecutionTime         = "queryExecutionTime"
	StagingTableName           = "stagingTableName"
	TotalRows                  = "totalRows"
	SampleDuplicateMessages    = "sampleDuplicateMessages"
	IntervalInHours            = "intervalInHours"
	StartTime                  = "startTime"
	EndTime                    = "endTime"
	ProjectID                  = "projectID"
)
