package logfield

const (
	UploadStatus               = "uploadStatus"
	UseRudderStorage           = "useRudderStorage"
	TaskRunID                  = "taskRunID"
	DestinationRevisionID      = "destinationRevisionID"
	DestinationValidationsStep = "step"
	Status                     = "status"
	ErrorCategory              = "errorCategory"
	TableName                  = "tableName"
	ColumnName                 = "columnName"
	ColumnType                 = "columnType"
	ColumnValue                = "columnValue"
	Priority                   = "priority"
	Retried                    = "retried"
	Attempt                    = "attempt"
	LoadFileType               = "loadFileType"
	ShouldMerge                = "shouldMerge"
	ErrorMapping               = "errorMapping"
	DestinationCredsValid      = "destinationCredsValid"
	Query                      = "query"
	QueryExecutionTime         = "queryExecutionTime"
	StagingTableName           = "stagingTableName"
	TotalRows                  = "totalRows"
	SampleDuplicateMessages    = "sampleDuplicateMessages"
	IntervalInHours            = "intervalInHours"
	StartTime                  = "startTime"
	EndTime                    = "endTime"
)
