version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 4
      semver-patch-days: 2
      exclude:
        - "github.com/rudderlabs/*"
    groups:
      frequent:
        patterns:
          - "github.com/aws/aws-sdk-go"
          - "google.golang.org/api"
          - "cloud.google.com/go/*"
      go-deps:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 4
      exclude:
        - "rudderlabs/*"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 4
      exclude:
        - "rudderstack/*"
        - "rudderlabs/*"
    groups:
      docker-deps:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
