version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/" 
    schedule:
      interval: "daily"
    groups:
      frequent:
        patterns:
          - "github.com/aws/aws-sdk-go"
          - "google.golang.org/api"
          - "cloud.google.com/go/*"
      go-deps:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/" 
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/" 
    schedule:
      interval: "daily"
    groups:
      docker-deps:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: docker
    directory: /cmd/benchmark
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /processor/internal/transformer/destination_transformer/embedded/warehouse/benchmark
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /services/streammanager/kafka/testdata/aiokafka
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /services/streammanager/kafka/testdata/aiokafka
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /suppression-backup-service
    schedule:
      interval: daily
