version = 1

test_patterns = [
    "**/*_test.go",
    "tests/**"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/rudderlabs/rudder-server"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  dialect = "typescript"
  environment = ["browser"]
