version = 1

test_patterns = [
    "**/*_test.go",
    "tests/**"
]

exclude_patterns = [
  "**/mock_*.go",
  "**/*.pb.go"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/rudderlabs/rudder-server"]

