run:
  timeout: 5m
  go: '1.18'
  skip-dirs:
    - warehouse
    - enterprise

linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - bodyclose
    - decorder
    - makezero
