run:
  timeout: 5m
  go: '1.18'
  skip-dirs:
    - warehouse
    - event-schema

linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
