run:
  timeout: 5m
  go: '1.19'
  skip-dirs:
    - enterprise
    - event-schema

linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - bodyclose
    - decorder
    - makezero
    - nilnil
    - nilerr
    - rowserrcheck
    - tenv
    - wastedassign
    - unparam
    - misspell
    - unconvert

issues:
  exclude-use-default: true
  exclude-case-sensitive: false
  max-issues-per-linter: 50
  max-same-issues: 10
  new: false
  exclude-rules: 
    # False positive httptest.NewRecorder
    - path: 'gateway/webhook/webhook_test.go'
      linters:
        - bodyclose
  
    # False positive .Close behind if
    - path: 'processor/transformer/transformer.go'
      linters:
        - bodyclose
    
    # False positive httptest.NewRecorder
    - path: 'gateway/gateway_test.go'
      linters:
        - bodyclose

    # Temporary disable until we fix the number of issues
    - path: 'warehouse'
      linters:
        - errcheck
        - unparam
