version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/rudder-server
permissions:
  - object:  /home/ubuntu/rudder-server
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 120
