ARG GO_VERSION=1.17
FROM golang:${GO_VERSION} AS builder
COPY download.sh .
RUN ["chmod", "+x", "download.sh"]
RUN ./download.sh --install
ARG VERSION
ARG REVISION
ARG COMMIT_HASH
ARG RACE_ENABLED=false
ARG CGO_ENABLED=1
ARG PKG_NAME=github.com/rudderlabs/release-demo

WORKDIR /rudder-server

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . . 

RUN ld -lobjectbox --verbose
RUN LDFLAGS="-s -w -L /usr/lib/libobjectbox.so" \
    make build

FROM golang:${GO_VERSION}
RUN apt-get update
RUN apt-get install ca-certificates
RUN apt-get install -y postgresql-client

COPY download.sh .
RUN ["chmod", "+x", "download.sh"]
RUN ./download.sh --install

RUN ld -lobjectbox --verbose
COPY --from=builder rudder-server/rudder-server .
COPY --from=builder rudder-server/build/wait-for-go/wait-for-go .
COPY --from=builder rudder-server/build/regulation-worker . 


COPY build/docker-entrypoint.sh /
COPY build/wait-for /
COPY ./rudder-cli/rudder-cli.linux.x86_64 /usr/bin/rudder-cli
COPY scripts/generate-event /scripts
COPY scripts/batch.json /scripts
RUN ls -l

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["/rudder-server"]