version: "3.7"

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    entrypoint: sh -c 'go run -mod=vendor main.go'
    ports:
      - "8080:8080"
    env_file:
      - build/docker.env
