version: "2.1"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=jobsdb
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=rudder
    ports:
      - "5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      retries: 25
  transformer:
    image: rudderlabs/develop-rudder-transformer:master
    ports:
      - "9090"
  minio:
    image: minio/minio:latest
    ports:
      - "9000/tcp"
    environment:
      - MINIO_ACCESS_KEY=MYACCESSKEY
      - MINIO_SECRET_KEY=MYSECRETKEY
      - MINIO_SITE_REGION=us-east-1
    command: server /data
    healthcheck:
      test: curl --fail http://localhost:9000/minio/health/live || exit 1
      interval: 1s
      retries: 25
