// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/processor/transformer (interfaces: UserClient)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/processor/transformer/mock_user_client.go -package=mocks_transformer github.com/rudderlabs/rudder-server/processor/transformer UserClient
//

// Package mocks_transformer is a generated GoMock package.
package mocks_transformer

import (
	context "context"
	reflect "reflect"

	types "github.com/rudderlabs/rudder-server/processor/types"
	gomock "go.uber.org/mock/gomock"
)

// MockUserClient is a mock of UserClient interface.
type MockUserClient struct {
	ctrl     *gomock.Controller
	recorder *MockUserClientMockRecorder
	isgomock struct{}
}

// MockUserClientMockRecorder is the mock recorder for MockUserClient.
type MockUserClientMockRecorder struct {
	mock *MockUserClient
}

// NewMockUserClient creates a new mock instance.
func NewMockUserClient(ctrl *gomock.Controller) *MockUserClient {
	mock := &MockUserClient{ctrl: ctrl}
	mock.recorder = &MockUserClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserClient) EXPECT() *MockUserClientMockRecorder {
	return m.recorder
}

// Transform mocks base method.
func (m *MockUserClient) Transform(ctx context.Context, events []types.TransformerEvent) types.Response {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transform", ctx, events)
	ret0, _ := ret[0].(types.Response)
	return ret0
}

// Transform indicates an expected call of Transform.
func (mr *MockUserClientMockRecorder) Transform(ctx, events any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transform", reflect.TypeOf((*MockUserClient)(nil).Transform), ctx, events)
}
