// Code generated by ObjectBox; DO NOT EDIT.
// Learn more about defining entities and generating this file - visit https://golang.objectbox.io/entity-annotations

package objectdb

import (
	"encoding/json"
	"errors"
	"github.com/google/flatbuffers/go"
	"github.com/objectbox/objectbox-go/objectbox"
	"github.com/objectbox/objectbox-go/objectbox/fbutils"
)

type gatewayJob_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var GatewayJobBinding = gatewayJob_EntityInfo{
	Entity: objectbox.Entity{
		Id: 11,
	},
	Uid: 8983575162441289249,
}

// GatewayJob_ contains type-based Property helpers to facilitate some common operations such as Queries.
var GatewayJob_ = struct {
	JobID                   *objectbox.PropertyUint64
	UserID                  *objectbox.PropertyString
	CustomVal               *objectbox.PropertyString
	WorkspaceID             *objectbox.PropertyString
	ReceivedAt              *objectbox.PropertyInt64
	CreatedAt               *objectbox.PropertyInt64
	ExpireAt                *objectbox.PropertyInt64
	EventCount              *objectbox.PropertyInt
	EventPayload            *objectbox.PropertyByteVector
	PayloadSize             *objectbox.PropertyInt64
	JobState                *objectbox.PropertyString
	Stage                   *objectbox.PropertyString
	StatusCode              *objectbox.PropertyInt
	AttemptNum              *objectbox.PropertyInt
	FirstAttemptedAt        *objectbox.PropertyInt64
	ExecTime                *objectbox.PropertyInt64
	RetryTime               *objectbox.PropertyInt64
	ErrorResponse           *objectbox.PropertyByteVector
	WriteKey                *objectbox.PropertyString
	IPAddress               *objectbox.PropertyString
	SourceID                *objectbox.PropertyString
	DestinationID           *objectbox.PropertyString
	SourceBatchID           *objectbox.PropertyString
	SourceTaskID            *objectbox.PropertyString
	SourceTaskRunID         *objectbox.PropertyString
	SourceJobID             *objectbox.PropertyString
	SourceJobRunID          *objectbox.PropertyString
	SourceDefinitionID      *objectbox.PropertyString
	DestinationDefinitionID *objectbox.PropertyString
	SourceCategory          *objectbox.PropertyString
	EventName               *objectbox.PropertyString
	EventType               *objectbox.PropertyString
	MessageID               *objectbox.PropertyString
	TransformAt             *objectbox.PropertyString
	RecordID                *objectbox.PropertyByteVector
}{
	JobID: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &GatewayJobBinding.Entity,
		},
	},
	UserID: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &GatewayJobBinding.Entity,
		},
	},
	CustomVal: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     3,
			Entity: &GatewayJobBinding.Entity,
		},
	},
	WorkspaceID: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     4,
			Entity: &GatewayJobBinding.Entity,
		},
	},
	ReceivedAt: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     5,
			Entity: &GatewayJobBinding.Entity,
		},
	},
	CreatedAt: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     6,
			Entity: &GatewayJobBinding.Entity,
		},
	},
	ExpireAt: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     7,
			Entity: &GatewayJobBinding.Entity,
		},
	},
	EventCount: &objectbox.PropertyInt{
		BaseProperty: &objectbox.BaseProperty{
			Id:     8,
			Entity: &GatewayJobBinding.Entity,
		},
	},
	EventPayload: &objectbox.PropertyByteVector{
		BaseProperty: &objectbox.BaseProperty{
			Id:     9,
			Entity: &GatewayJobBinding.Entity,
		},
	},
	PayloadSize: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     10,
			Entity: &GatewayJobBinding.Entity,
		},
	},
	JobState: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     11,
			Entity: &GatewayJobBinding.Entity,
		},
	},
	Stage: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     12,
			Entity: &GatewayJobBinding.Entity,
		},
	},
	StatusCode: &objectbox.PropertyInt{
		BaseProperty: &objectbox.BaseProperty{
			Id:     13,
			Entity: &GatewayJobBinding.Entity,
		},
	},
	AttemptNum: &objectbox.PropertyInt{
		BaseProperty: &objectbox.BaseProperty{
			Id:     14,
			Entity: &GatewayJobBinding.Entity,
		},
	},
	FirstAttemptedAt: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     15,
			Entity: &GatewayJobBinding.Entity,
		},
	},
	ExecTime: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     16,
			Entity: &GatewayJobBinding.Entity,
		},
	},
	RetryTime: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     17,
			Entity: &GatewayJobBinding.Entity,
		},
	},
	ErrorResponse: &objectbox.PropertyByteVector{
		BaseProperty: &objectbox.BaseProperty{
			Id:     18,
			Entity: &GatewayJobBinding.Entity,
		},
	},
	WriteKey: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     19,
			Entity: &GatewayJobBinding.Entity,
		},
	},
	IPAddress: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     20,
			Entity: &GatewayJobBinding.Entity,
		},
	},
	SourceID: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     21,
			Entity: &GatewayJobBinding.Entity,
		},
	},
	DestinationID: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     22,
			Entity: &GatewayJobBinding.Entity,
		},
	},
	SourceBatchID: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     23,
			Entity: &GatewayJobBinding.Entity,
		},
	},
	SourceTaskID: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     24,
			Entity: &GatewayJobBinding.Entity,
		},
	},
	SourceTaskRunID: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     25,
			Entity: &GatewayJobBinding.Entity,
		},
	},
	SourceJobID: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     26,
			Entity: &GatewayJobBinding.Entity,
		},
	},
	SourceJobRunID: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     27,
			Entity: &GatewayJobBinding.Entity,
		},
	},
	SourceDefinitionID: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     28,
			Entity: &GatewayJobBinding.Entity,
		},
	},
	DestinationDefinitionID: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     29,
			Entity: &GatewayJobBinding.Entity,
		},
	},
	SourceCategory: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     30,
			Entity: &GatewayJobBinding.Entity,
		},
	},
	EventName: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     31,
			Entity: &GatewayJobBinding.Entity,
		},
	},
	EventType: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     32,
			Entity: &GatewayJobBinding.Entity,
		},
	},
	MessageID: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     33,
			Entity: &GatewayJobBinding.Entity,
		},
	},
	TransformAt: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     34,
			Entity: &GatewayJobBinding.Entity,
		},
	},
	RecordID: &objectbox.PropertyByteVector{
		BaseProperty: &objectbox.BaseProperty{
			Id:     35,
			Entity: &GatewayJobBinding.Entity,
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (gatewayJob_EntityInfo) GeneratorVersion() int {
	return 6
}

// AddToModel is called by ObjectBox during model build
func (gatewayJob_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("GatewayJob", 11, 8983575162441289249)
	model.Property("JobID", 6, 1, 789043973494019919)
	model.PropertyFlags(1)
	model.Property("UserID", 9, 2, 6351250238791673515)
	model.Property("CustomVal", 9, 3, 674180012179557301)
	model.PropertyFlags(2048)
	model.PropertyIndex(11, 6899325090046731766)
	model.Property("WorkspaceID", 9, 4, 9020652261408667992)
	model.PropertyFlags(2048)
	model.PropertyIndex(12, 2214883167717205299)
	model.Property("ReceivedAt", 10, 5, 4332330838421034489)
	model.Property("CreatedAt", 10, 6, 7921584148077040753)
	model.Property("ExpireAt", 10, 7, 5965725136339787544)
	model.Property("EventCount", 6, 8, 4791002015619641454)
	model.Property("EventPayload", 23, 9, 253995693023954894)
	model.Property("PayloadSize", 6, 10, 8147715355735398686)
	model.Property("JobState", 9, 11, 1085896188999012878)
	model.PropertyFlags(2048)
	model.PropertyIndex(13, 7230476407062915113)
	model.Property("Stage", 9, 12, 7336034814067846227)
	model.PropertyFlags(2048)
	model.PropertyIndex(14, 8888043941572274648)
	model.Property("StatusCode", 6, 13, 8147725470459656638)
	model.Property("AttemptNum", 6, 14, 3793112977013362345)
	model.Property("FirstAttemptedAt", 10, 15, 6932036748442026711)
	model.Property("ExecTime", 10, 16, 1232474605583436666)
	model.Property("RetryTime", 10, 17, 5302169635131451762)
	model.Property("ErrorResponse", 23, 18, 7095034305667563474)
	model.Property("WriteKey", 9, 19, 8130298215864939603)
	model.Property("IPAddress", 9, 20, 6226892702387744321)
	model.Property("SourceID", 9, 21, 2907563310946296642)
	model.Property("DestinationID", 9, 22, 2995053329389291345)
	model.Property("SourceBatchID", 9, 23, 4064819716290424031)
	model.Property("SourceTaskID", 9, 24, 2069755460011421807)
	model.Property("SourceTaskRunID", 9, 25, 4869202125740458753)
	model.Property("SourceJobID", 9, 26, 5077694453945093341)
	model.Property("SourceJobRunID", 9, 27, 4518365308404908831)
	model.Property("SourceDefinitionID", 9, 28, 285913776182025651)
	model.Property("DestinationDefinitionID", 9, 29, 6812529101841799629)
	model.Property("SourceCategory", 9, 30, 1144522436567163255)
	model.Property("EventName", 9, 31, 3430988829732338860)
	model.Property("EventType", 9, 32, 3356101081643654202)
	model.Property("MessageID", 9, 33, 1257250103980808641)
	model.Property("TransformAt", 9, 34, 2543207056438922206)
	model.Property("RecordID", 23, 35, 37061741945093667)
	model.EntityLastPropertyId(35, 37061741945093667)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (gatewayJob_EntityInfo) GetId(object interface{}) (uint64, error) {
	return object.(*GatewayJob).JobID, nil
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (gatewayJob_EntityInfo) SetId(object interface{}, id uint64) error {
	object.(*GatewayJob).JobID = id
	return nil
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (gatewayJob_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (gatewayJob_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*GatewayJob)
	var propReceivedAt int64
	{
		var err error
		propReceivedAt, err = objectbox.TimeInt64ConvertToDatabaseValue(obj.ReceivedAt)
		if err != nil {
			return errors.New("converter objectbox.TimeInt64ConvertToDatabaseValue() failed on GatewayJob.ReceivedAt: " + err.Error())
		}
	}

	var propCreatedAt int64
	{
		var err error
		propCreatedAt, err = objectbox.TimeInt64ConvertToDatabaseValue(obj.CreatedAt)
		if err != nil {
			return errors.New("converter objectbox.TimeInt64ConvertToDatabaseValue() failed on GatewayJob.CreatedAt: " + err.Error())
		}
	}

	var propExpireAt int64
	{
		var err error
		propExpireAt, err = objectbox.TimeInt64ConvertToDatabaseValue(obj.ExpireAt)
		if err != nil {
			return errors.New("converter objectbox.TimeInt64ConvertToDatabaseValue() failed on GatewayJob.ExpireAt: " + err.Error())
		}
	}

	var propFirstAttemptedAt int64
	{
		var err error
		propFirstAttemptedAt, err = objectbox.TimeInt64ConvertToDatabaseValue(obj.FirstAttemptedAt)
		if err != nil {
			return errors.New("converter objectbox.TimeInt64ConvertToDatabaseValue() failed on GatewayJob.FirstAttemptedAt: " + err.Error())
		}
	}

	var propExecTime int64
	{
		var err error
		propExecTime, err = objectbox.TimeInt64ConvertToDatabaseValue(obj.ExecTime)
		if err != nil {
			return errors.New("converter objectbox.TimeInt64ConvertToDatabaseValue() failed on GatewayJob.ExecTime: " + err.Error())
		}
	}

	var propRetryTime int64
	{
		var err error
		propRetryTime, err = objectbox.TimeInt64ConvertToDatabaseValue(obj.RetryTime)
		if err != nil {
			return errors.New("converter objectbox.TimeInt64ConvertToDatabaseValue() failed on GatewayJob.RetryTime: " + err.Error())
		}
	}

	var offsetUserID = fbutils.CreateStringOffset(fbb, obj.UserID)
	var offsetCustomVal = fbutils.CreateStringOffset(fbb, obj.CustomVal)
	var offsetWorkspaceID = fbutils.CreateStringOffset(fbb, obj.WorkspaceID)
	var offsetEventPayload = fbutils.CreateByteVectorOffset(fbb, []byte(obj.EventPayload))
	var offsetJobState = fbutils.CreateStringOffset(fbb, obj.JobState)
	var offsetStage = fbutils.CreateStringOffset(fbb, obj.Stage)
	var offsetErrorResponse = fbutils.CreateByteVectorOffset(fbb, []byte(obj.ErrorResponse))
	var offsetWriteKey = fbutils.CreateStringOffset(fbb, obj.WriteKey)
	var offsetIPAddress = fbutils.CreateStringOffset(fbb, obj.IPAddress)
	var offsetSourceID = fbutils.CreateStringOffset(fbb, obj.SourceID)
	var offsetDestinationID = fbutils.CreateStringOffset(fbb, obj.DestinationID)
	var offsetSourceBatchID = fbutils.CreateStringOffset(fbb, obj.SourceBatchID)
	var offsetSourceTaskID = fbutils.CreateStringOffset(fbb, obj.SourceTaskID)
	var offsetSourceTaskRunID = fbutils.CreateStringOffset(fbb, obj.SourceTaskRunID)
	var offsetSourceJobID = fbutils.CreateStringOffset(fbb, obj.SourceJobID)
	var offsetSourceJobRunID = fbutils.CreateStringOffset(fbb, obj.SourceJobRunID)
	var offsetSourceDefinitionID = fbutils.CreateStringOffset(fbb, obj.SourceDefinitionID)
	var offsetDestinationDefinitionID = fbutils.CreateStringOffset(fbb, obj.DestinationDefinitionID)
	var offsetSourceCategory = fbutils.CreateStringOffset(fbb, obj.SourceCategory)
	var offsetEventName = fbutils.CreateStringOffset(fbb, obj.EventName)
	var offsetEventType = fbutils.CreateStringOffset(fbb, obj.EventType)
	var offsetMessageID = fbutils.CreateStringOffset(fbb, obj.MessageID)
	var offsetTransformAt = fbutils.CreateStringOffset(fbb, obj.TransformAt)
	var offsetRecordID = fbutils.CreateByteVectorOffset(fbb, []byte(obj.RecordID))

	// build the FlatBuffers object
	fbb.StartObject(35)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetUOffsetTSlot(fbb, 1, offsetUserID)
	fbutils.SetUOffsetTSlot(fbb, 2, offsetCustomVal)
	fbutils.SetUOffsetTSlot(fbb, 3, offsetWorkspaceID)
	fbutils.SetInt64Slot(fbb, 4, propReceivedAt)
	fbutils.SetInt64Slot(fbb, 5, propCreatedAt)
	fbutils.SetInt64Slot(fbb, 6, propExpireAt)
	fbutils.SetInt64Slot(fbb, 7, int64(obj.EventCount))
	fbutils.SetUOffsetTSlot(fbb, 8, offsetEventPayload)
	fbutils.SetInt64Slot(fbb, 9, obj.PayloadSize)
	fbutils.SetUOffsetTSlot(fbb, 10, offsetJobState)
	fbutils.SetUOffsetTSlot(fbb, 11, offsetStage)
	fbutils.SetInt64Slot(fbb, 12, int64(obj.StatusCode))
	fbutils.SetInt64Slot(fbb, 13, int64(obj.AttemptNum))
	fbutils.SetInt64Slot(fbb, 14, propFirstAttemptedAt)
	fbutils.SetInt64Slot(fbb, 15, propExecTime)
	fbutils.SetInt64Slot(fbb, 16, propRetryTime)
	fbutils.SetUOffsetTSlot(fbb, 17, offsetErrorResponse)
	fbutils.SetUOffsetTSlot(fbb, 18, offsetWriteKey)
	fbutils.SetUOffsetTSlot(fbb, 19, offsetIPAddress)
	fbutils.SetUOffsetTSlot(fbb, 20, offsetSourceID)
	fbutils.SetUOffsetTSlot(fbb, 21, offsetDestinationID)
	fbutils.SetUOffsetTSlot(fbb, 22, offsetSourceBatchID)
	fbutils.SetUOffsetTSlot(fbb, 23, offsetSourceTaskID)
	fbutils.SetUOffsetTSlot(fbb, 24, offsetSourceTaskRunID)
	fbutils.SetUOffsetTSlot(fbb, 25, offsetSourceJobID)
	fbutils.SetUOffsetTSlot(fbb, 26, offsetSourceJobRunID)
	fbutils.SetUOffsetTSlot(fbb, 27, offsetSourceDefinitionID)
	fbutils.SetUOffsetTSlot(fbb, 28, offsetDestinationDefinitionID)
	fbutils.SetUOffsetTSlot(fbb, 29, offsetSourceCategory)
	fbutils.SetUOffsetTSlot(fbb, 30, offsetEventName)
	fbutils.SetUOffsetTSlot(fbb, 31, offsetEventType)
	fbutils.SetUOffsetTSlot(fbb, 32, offsetMessageID)
	fbutils.SetUOffsetTSlot(fbb, 33, offsetTransformAt)
	fbutils.SetUOffsetTSlot(fbb, 34, offsetRecordID)
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (gatewayJob_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	if len(bytes) == 0 { // sanity check, should "never" happen
		return nil, errors.New("can't deserialize an object of type 'GatewayJob' - no data received")
	}

	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	var propJobID = table.GetUint64Slot(4, 0)

	propReceivedAt, err := objectbox.TimeInt64ConvertToEntityProperty(fbutils.GetInt64Slot(table, 12))
	if err != nil {
		return nil, errors.New("converter objectbox.TimeInt64ConvertToEntityProperty() failed on GatewayJob.ReceivedAt: " + err.Error())
	}

	propCreatedAt, err := objectbox.TimeInt64ConvertToEntityProperty(fbutils.GetInt64Slot(table, 14))
	if err != nil {
		return nil, errors.New("converter objectbox.TimeInt64ConvertToEntityProperty() failed on GatewayJob.CreatedAt: " + err.Error())
	}

	propExpireAt, err := objectbox.TimeInt64ConvertToEntityProperty(fbutils.GetInt64Slot(table, 16))
	if err != nil {
		return nil, errors.New("converter objectbox.TimeInt64ConvertToEntityProperty() failed on GatewayJob.ExpireAt: " + err.Error())
	}

	propFirstAttemptedAt, err := objectbox.TimeInt64ConvertToEntityProperty(fbutils.GetInt64Slot(table, 32))
	if err != nil {
		return nil, errors.New("converter objectbox.TimeInt64ConvertToEntityProperty() failed on GatewayJob.FirstAttemptedAt: " + err.Error())
	}

	propExecTime, err := objectbox.TimeInt64ConvertToEntityProperty(fbutils.GetInt64Slot(table, 34))
	if err != nil {
		return nil, errors.New("converter objectbox.TimeInt64ConvertToEntityProperty() failed on GatewayJob.ExecTime: " + err.Error())
	}

	propRetryTime, err := objectbox.TimeInt64ConvertToEntityProperty(fbutils.GetInt64Slot(table, 36))
	if err != nil {
		return nil, errors.New("converter objectbox.TimeInt64ConvertToEntityProperty() failed on GatewayJob.RetryTime: " + err.Error())
	}

	return &GatewayJob{
		JobID:                   propJobID,
		UserID:                  fbutils.GetStringSlot(table, 6),
		CustomVal:               fbutils.GetStringSlot(table, 8),
		WorkspaceID:             fbutils.GetStringSlot(table, 10),
		ReceivedAt:              propReceivedAt,
		CreatedAt:               propCreatedAt,
		ExpireAt:                propExpireAt,
		EventCount:              fbutils.GetIntSlot(table, 18),
		EventPayload:            json.RawMessage(fbutils.GetByteVectorSlot(table, 20)),
		PayloadSize:             fbutils.GetInt64Slot(table, 22),
		JobState:                fbutils.GetStringSlot(table, 24),
		Stage:                   fbutils.GetStringSlot(table, 26),
		StatusCode:              fbutils.GetIntSlot(table, 28),
		AttemptNum:              fbutils.GetIntSlot(table, 30),
		FirstAttemptedAt:        propFirstAttemptedAt,
		ExecTime:                propExecTime,
		RetryTime:               propRetryTime,
		ErrorResponse:           json.RawMessage(fbutils.GetByteVectorSlot(table, 38)),
		WriteKey:                fbutils.GetStringSlot(table, 40),
		IPAddress:               fbutils.GetStringSlot(table, 42),
		SourceID:                fbutils.GetStringSlot(table, 44),
		DestinationID:           fbutils.GetStringSlot(table, 46),
		SourceBatchID:           fbutils.GetStringSlot(table, 48),
		SourceTaskID:            fbutils.GetStringSlot(table, 50),
		SourceTaskRunID:         fbutils.GetStringSlot(table, 52),
		SourceJobID:             fbutils.GetStringSlot(table, 54),
		SourceJobRunID:          fbutils.GetStringSlot(table, 56),
		SourceDefinitionID:      fbutils.GetStringSlot(table, 58),
		DestinationDefinitionID: fbutils.GetStringSlot(table, 60),
		SourceCategory:          fbutils.GetStringSlot(table, 62),
		EventName:               fbutils.GetStringSlot(table, 64),
		EventType:               fbutils.GetStringSlot(table, 66),
		MessageID:               fbutils.GetStringSlot(table, 68),
		TransformAt:             fbutils.GetStringSlot(table, 70),
		RecordID:                json.RawMessage(fbutils.GetByteVectorSlot(table, 72)),
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (gatewayJob_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*GatewayJob, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (gatewayJob_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	if object == nil {
		return append(slice.([]*GatewayJob), nil)
	}
	return append(slice.([]*GatewayJob), object.(*GatewayJob))
}

// Box provides CRUD access to GatewayJob objects
type GatewayJobBox struct {
	*objectbox.Box
}

// BoxForGatewayJob opens a box of GatewayJob objects
func BoxForGatewayJob(ob *objectbox.ObjectBox) *GatewayJobBox {
	return &GatewayJobBox{
		Box: ob.InternalBox(11),
	}
}

// Put synchronously inserts/updates a single object.
// In case the JobID is not specified, it would be assigned automatically (auto-increment).
// When inserting, the GatewayJob.JobID property on the passed object will be assigned the new ID as well.
func (box *GatewayJobBox) Put(object *GatewayJob) (uint64, error) {
	return box.Box.Put(object)
}

// Insert synchronously inserts a single object. As opposed to Put, Insert will fail if given an ID that already exists.
// In case the JobID is not specified, it would be assigned automatically (auto-increment).
// When inserting, the GatewayJob.JobID property on the passed object will be assigned the new ID as well.
func (box *GatewayJobBox) Insert(object *GatewayJob) (uint64, error) {
	return box.Box.Insert(object)
}

// Update synchronously updates a single object.
// As opposed to Put, Update will fail if an object with the same ID is not found in the database.
func (box *GatewayJobBox) Update(object *GatewayJob) error {
	return box.Box.Update(object)
}

// PutAsync asynchronously inserts/updates a single object.
// Deprecated: use box.Async().Put() instead
func (box *GatewayJobBox) PutAsync(object *GatewayJob) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case JobIDs are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the GatewayJob.JobID property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the GatewayJob.JobID assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *GatewayJobBox) PutMany(objects []*GatewayJob) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *GatewayJobBox) Get(id uint64) (*GatewayJob, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*GatewayJob), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is nil
func (box *GatewayJobBox) GetMany(ids ...uint64) ([]*GatewayJob, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*GatewayJob), nil
}

// GetManyExisting reads multiple objects at once, skipping those that do not exist.
func (box *GatewayJobBox) GetManyExisting(ids ...uint64) ([]*GatewayJob, error) {
	objects, err := box.Box.GetManyExisting(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*GatewayJob), nil
}

// GetAll reads all stored objects
func (box *GatewayJobBox) GetAll() ([]*GatewayJob, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]*GatewayJob), nil
}

// Remove deletes a single object
func (box *GatewayJobBox) Remove(object *GatewayJob) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *GatewayJobBox) RemoveMany(objects ...*GatewayJob) (uint64, error) {
	var ids = make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = object.JobID
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the GatewayJob_ struct to create conditions.
// Keep the *GatewayJobQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *GatewayJobBox) Query(conditions ...objectbox.Condition) *GatewayJobQuery {
	return &GatewayJobQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the GatewayJob_ struct to create conditions.
// Keep the *GatewayJobQuery if you intend to execute the query multiple times.
func (box *GatewayJobBox) QueryOrError(conditions ...objectbox.Condition) (*GatewayJobQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &GatewayJobQuery{query}, nil
	}
}

// Async provides access to the default Async Box for asynchronous operations. See GatewayJobAsyncBox for more information.
func (box *GatewayJobBox) Async() *GatewayJobAsyncBox {
	return &GatewayJobAsyncBox{AsyncBox: box.Box.Async()}
}

// GatewayJobAsyncBox provides asynchronous operations on GatewayJob objects.
//
// Asynchronous operations are executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "execute & forget:" you gain faster put/remove operations as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
// In situations with (extremely) high async load, an async method may be throttled (~1ms) or delayed up to 1 second.
// In the unlikely event that the object could still not be enqueued (full queue), an error will be returned.
//
// Note that async methods do not give you hard durability guarantees like the synchronous Box provides.
// There is a small time window in which the data may not have been committed durably yet.
type GatewayJobAsyncBox struct {
	*objectbox.AsyncBox
}

// AsyncBoxForGatewayJob creates a new async box with the given operation timeout in case an async queue is full.
// The returned struct must be freed explicitly using the Close() method.
// It's usually preferable to use GatewayJobBox::Async() which takes care of resource management and doesn't require closing.
func AsyncBoxForGatewayJob(ob *objectbox.ObjectBox, timeoutMs uint64) *GatewayJobAsyncBox {
	var async, err = objectbox.NewAsyncBox(ob, 11, timeoutMs)
	if err != nil {
		panic("Could not create async box for entity ID 11: %s" + err.Error())
	}
	return &GatewayJobAsyncBox{AsyncBox: async}
}

// Put inserts/updates a single object asynchronously.
// When inserting a new object, the JobID property on the passed object will be assigned the new ID the entity would hold
// if the insert is ultimately successful. The newly assigned ID may not become valid if the insert fails.
func (asyncBox *GatewayJobAsyncBox) Put(object *GatewayJob) (uint64, error) {
	return asyncBox.AsyncBox.Put(object)
}

// Insert a single object asynchronously.
// The JobID property on the passed object will be assigned the new ID the entity would hold if the insert is ultimately
// successful. The newly assigned ID may not become valid if the insert fails.
// Fails silently if an object with the same ID already exists (this error is not returned).
func (asyncBox *GatewayJobAsyncBox) Insert(object *GatewayJob) (id uint64, err error) {
	return asyncBox.AsyncBox.Insert(object)
}

// Update a single object asynchronously.
// The object must already exists or the update fails silently (without an error returned).
func (asyncBox *GatewayJobAsyncBox) Update(object *GatewayJob) error {
	return asyncBox.AsyncBox.Update(object)
}

// Remove deletes a single object asynchronously.
func (asyncBox *GatewayJobAsyncBox) Remove(object *GatewayJob) error {
	return asyncBox.AsyncBox.Remove(object)
}

// Query provides a way to search stored objects
//
// For example, you can find all GatewayJob which JobID is either 42 or 47:
// 		box.Query(GatewayJob_.JobID.In(42, 47)).Find()
type GatewayJobQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *GatewayJobQuery) Find() ([]*GatewayJob, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]*GatewayJob), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *GatewayJobQuery) Offset(offset uint64) *GatewayJobQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *GatewayJobQuery) Limit(limit uint64) *GatewayJobQuery {
	query.Query.Limit(limit)
	return query
}
