// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/router (interfaces: NetHandle)

// Package mock_network is a generated GoMock package.
package mock_network

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	integrations "github.com/rudderlabs/rudder-server/processor/integrations"
	types "github.com/rudderlabs/rudder-server/router/types"
	utils "github.com/rudderlabs/rudder-server/router/utils"
)

// MockNetHandle is a mock of NetHandle interface.
type MockNetHandle struct {
	ctrl     *gomock.Controller
	recorder *MockNetHandleMockRecorder
}

// MockNetHandleMockRecorder is the mock recorder for MockNetHandle.
type MockNetHandleMockRecorder struct {
	mock *MockNetHandle
}

// NewMockNetHandle creates a new mock instance.
func NewMockNetHandle(ctrl *gomock.Controller) *MockNetHandle {
	mock := &MockNetHandle{ctrl: ctrl}
	mock.recorder = &MockNetHandleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetHandle) EXPECT() *MockNetHandleMockRecorder {
	return m.recorder
}

// SendPost mocks base method.
func (m *MockNetHandle) SendPost(arg0 context.Context, arg1 integrations.PostParametersT, arg2 types.DestinationInfo) *utils.SendPostResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPost", arg0, arg1, arg2)
	ret0, _ := ret[0].(*utils.SendPostResponse)
	return ret0
}

// SendPost indicates an expected call of SendPost.
func (mr *MockNetHandleMockRecorder) SendPost(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPost", reflect.TypeOf((*MockNetHandle)(nil).SendPost), arg0, arg1, arg2)
}
