DROP INDEX IF EXISTS wh_load_files_source_destination_id_table_name_index;

DROP INDEX IF EXISTS wh_load_files_staging_file_id_table_name_index;

DROP INDEX IF EXISTS wh_uploads_id_destination_id_namespace_status_index;

DROP INDEX IF EXISTS wh_table_uploads_wh_upload_id_table_name_index;
