// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/router/batchrouter/asyncdestinationmanager/salesforce-bulk-upload (interfaces: APIServiceInterface)
//
// Generated by this command:
//
//	mockgen -destination=mocks/router/salesforce-bulk-upload/salesforce-bulk-upload_mock.go -package=salesforcebulkupload_mocks -mock_names=APIServiceInterface=MockSalesforceAPIService github.com/rudderlabs/rudder-server/router/batchrouter/asyncdestinationmanager/salesforce-bulk-upload APIServiceInterface
//

// Package salesforcebulkupload_mocks is a generated GoMock package.
package salesforcebulkupload_mocks

import (
	reflect "reflect"

	salesforcebulkupload "github.com/rudderlabs/rudder-server/router/batchrouter/asyncdestinationmanager/salesforce-bulk-upload"
	gomock "go.uber.org/mock/gomock"
)

// MockSalesforceAPIService is a mock of APIServiceInterface interface.
type MockSalesforceAPIService struct {
	ctrl     *gomock.Controller
	recorder *MockSalesforceAPIServiceMockRecorder
	isgomock struct{}
}

// MockSalesforceAPIServiceMockRecorder is the mock recorder for MockSalesforceAPIService.
type MockSalesforceAPIServiceMockRecorder struct {
	mock *MockSalesforceAPIService
}

// NewMockSalesforceAPIService creates a new mock instance.
func NewMockSalesforceAPIService(ctrl *gomock.Controller) *MockSalesforceAPIService {
	mock := &MockSalesforceAPIService{ctrl: ctrl}
	mock.recorder = &MockSalesforceAPIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSalesforceAPIService) EXPECT() *MockSalesforceAPIServiceMockRecorder {
	return m.recorder
}

// CloseJob mocks base method.
func (m *MockSalesforceAPIService) CloseJob(jobID string) *salesforcebulkupload.APIError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseJob", jobID)
	ret0, _ := ret[0].(*salesforcebulkupload.APIError)
	return ret0
}

// CloseJob indicates an expected call of CloseJob.
func (mr *MockSalesforceAPIServiceMockRecorder) CloseJob(jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseJob", reflect.TypeOf((*MockSalesforceAPIService)(nil).CloseJob), jobID)
}

// CreateJob mocks base method.
func (m *MockSalesforceAPIService) CreateJob(objectName, operation, externalIDField string) (string, *salesforcebulkupload.APIError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJob", objectName, operation, externalIDField)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*salesforcebulkupload.APIError)
	return ret0, ret1
}

// CreateJob indicates an expected call of CreateJob.
func (mr *MockSalesforceAPIServiceMockRecorder) CreateJob(objectName, operation, externalIDField any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJob", reflect.TypeOf((*MockSalesforceAPIService)(nil).CreateJob), objectName, operation, externalIDField)
}

// DeleteJob mocks base method.
func (m *MockSalesforceAPIService) DeleteJob(jobID string) *salesforcebulkupload.APIError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteJob", jobID)
	ret0, _ := ret[0].(*salesforcebulkupload.APIError)
	return ret0
}

// DeleteJob indicates an expected call of DeleteJob.
func (mr *MockSalesforceAPIServiceMockRecorder) DeleteJob(jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteJob", reflect.TypeOf((*MockSalesforceAPIService)(nil).DeleteJob), jobID)
}

// GetFailedRecords mocks base method.
func (m *MockSalesforceAPIService) GetFailedRecords(jobID string) ([]map[string]string, *salesforcebulkupload.APIError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFailedRecords", jobID)
	ret0, _ := ret[0].([]map[string]string)
	ret1, _ := ret[1].(*salesforcebulkupload.APIError)
	return ret0, ret1
}

// GetFailedRecords indicates an expected call of GetFailedRecords.
func (mr *MockSalesforceAPIServiceMockRecorder) GetFailedRecords(jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFailedRecords", reflect.TypeOf((*MockSalesforceAPIService)(nil).GetFailedRecords), jobID)
}

// GetJobStatus mocks base method.
func (m *MockSalesforceAPIService) GetJobStatus(jobID string) (*salesforcebulkupload.JobResponse, *salesforcebulkupload.APIError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobStatus", jobID)
	ret0, _ := ret[0].(*salesforcebulkupload.JobResponse)
	ret1, _ := ret[1].(*salesforcebulkupload.APIError)
	return ret0, ret1
}

// GetJobStatus indicates an expected call of GetJobStatus.
func (mr *MockSalesforceAPIServiceMockRecorder) GetJobStatus(jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobStatus", reflect.TypeOf((*MockSalesforceAPIService)(nil).GetJobStatus), jobID)
}

// GetSuccessfulRecords mocks base method.
func (m *MockSalesforceAPIService) GetSuccessfulRecords(jobID string) ([]map[string]string, *salesforcebulkupload.APIError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSuccessfulRecords", jobID)
	ret0, _ := ret[0].([]map[string]string)
	ret1, _ := ret[1].(*salesforcebulkupload.APIError)
	return ret0, ret1
}

// GetSuccessfulRecords indicates an expected call of GetSuccessfulRecords.
func (mr *MockSalesforceAPIServiceMockRecorder) GetSuccessfulRecords(jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSuccessfulRecords", reflect.TypeOf((*MockSalesforceAPIService)(nil).GetSuccessfulRecords), jobID)
}

// UploadData mocks base method.
func (m *MockSalesforceAPIService) UploadData(jobID, csvFilePath string) *salesforcebulkupload.APIError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadData", jobID, csvFilePath)
	ret0, _ := ret[0].(*salesforcebulkupload.APIError)
	return ret0
}

// UploadData indicates an expected call of UploadData.
func (mr *MockSalesforceAPIServiceMockRecorder) UploadData(jobID, csvFilePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadData", reflect.TypeOf((*MockSalesforceAPIService)(nil).UploadData), jobID, csvFilePath)
}
