ALTER TABLE reports
ADD COLUMN IF NOT EXISTS source_category TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS source_definition_id TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS destination_definition_id TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS event_name TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS event_type TEXT DEFAULT '';
