// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/enterprise/reporting (interfaces: ErrorLimiter)
//
// Generated by this command:
//
//	mockgen -destination=mocks/enterprise/reporting/mock_error_limiter.go -package=mocks github.com/rudderlabs/rudder-server/enterprise/reporting ErrorLimiter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockErrorLimiter is a mock of ErrorLimiter interface.
type MockErrorLimiter struct {
	ctrl     *gomock.Controller
	recorder *MockErrorLimiterMockRecorder
	isgomock struct{}
}

// MockErrorLimiterMockRecorder is the mock recorder for MockErrorLimiter.
type MockErrorLimiterMockRecorder struct {
	mock *MockErrorLimiter
}

// NewMockErrorLimiter creates a new mock instance.
func NewMockErrorLimiter(ctrl *gomock.Controller) *MockErrorLimiter {
	mock := &MockErrorLimiter{ctrl: ctrl}
	mock.recorder = &MockErrorLimiterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockErrorLimiter) EXPECT() *MockErrorLimiterMockRecorder {
	return m.recorder
}

// CanonicalizeError mocks base method.
func (m *MockErrorLimiter) CanonicalizeError(ctx context.Context, connectionKey, errorMessage string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanonicalizeError", ctx, connectionKey, errorMessage)
	ret0, _ := ret[0].(string)
	return ret0
}

// CanonicalizeError indicates an expected call of CanonicalizeError.
func (mr *MockErrorLimiterMockRecorder) CanonicalizeError(ctx, connectionKey, errorMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanonicalizeError", reflect.TypeOf((*MockErrorLimiter)(nil).CanonicalizeError), ctx, connectionKey, errorMessage)
}

// StartCleanup mocks base method.
func (m *MockErrorLimiter) StartCleanup(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartCleanup", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartCleanup indicates an expected call of StartCleanup.
func (mr *MockErrorLimiterMockRecorder) StartCleanup(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartCleanup", reflect.TypeOf((*MockErrorLimiter)(nil).StartCleanup), ctx)
}
