#!/bin/sh

source .enterprise/env

# Check enterprise repo is loaded
if [ ! -d "$ENTERPRISE_DIR" ]; then
  exit 0
fi

# Check if enterprise repo has different commit
STORED_COMMIT=`cat $ENTERPRISE_COMMIT_FILE`
CURRENT_COMMIT=`cd $ENTERPRISE_DIR; git rev-parse HEAD`
CURRENT_ENTERPRISE_BRANCH=`cd $ENTERPRISE_DIR; git rev-parse --abbrev-ref HEAD`

if [ "$STORED_COMMIT" = "$CURRENT_COMMIT" ]; then
  exit 0
fi

echo "Enterprise repo commit hash is different than what is stored in current commit."
echo
echo "Stored commit hash:            $STORED_COMMIT"
echo "Enterprise repo commit hash:   $CURRENT_COMMIT"
echo "Enterprise repo branch:        $CURRENT_ENTERPRISE_BRANCH"
echo

exec < /dev/tty
read -p "Would you like to update to '$CURRENT_COMMIT'? (y/N) " -n 1 -r
echo
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
  .enterprise/scripts/update-commit.sh || exit 1
  git add $ENTERPRISE_COMMIT_FILE
  echo "Enterprise repo commit hash updated and staged."
fi