package testhelper

const (
	identifiesTemplate   = `{"data": {"id": "{{.msgID}}", "sent_at": "2023-05-09T15:54:16.022Z", "trait_1": "new-val", "user_id": "{{.userID}}", "timestamp": "2020-02-02T00:23:09.544Z", "context_ip": "[::1]", "received_at": "2023-05-09T15:54:14.846Z", "context_source_id": "{{.sourceID}}", "context_request_ip": "[::1]", "original_timestamp": "2023-05-09T15:54:16.022Z", "context_source_type": "Javascript", "context_destination_id": "{{.destID}}", "context_traits_trait_1": "new-val", "context_destination_type": "{{.destType}}"}, "userId": "", "metadata": {"table": "identifies", "columns": {"id": "string", "sent_at": "datetime", "trait_1": "string", "user_id": "string", "uuid_ts": "datetime", "timestamp": "datetime", "context_ip": "string", "received_at": "datetime", "context_source_id": "string", "context_request_ip": "string", "original_timestamp": "datetime", "context_source_type": "string", "context_destination_id": "string", "context_traits_trait_1": "string", "context_destination_type": "string", "uuid_ts": "datetime", "loaded_at": "datetime"}, "receivedAt": "2023-05-09T21:24:14.846+05:30"}}`
	usersTemplate        = `{"data": {"id": "{{.userID}}", "trait_1": "new-val", "context_ip": "[::1]", "received_at": "2023-05-09T15:54:14.846Z", "context_source_id": "{{.sourceID}}", "context_request_ip": "[::1]", "context_source_type": "Javascript", "context_destination_id": "{{.destID}}", "context_traits_trait_1": "new-val", "context_destination_type": "{{.destType}}"}, "userId": "", "metadata": {"table": "users", "columns": {"id": "string", "trait_1": "string", "uuid_ts": "datetime", "context_ip": "string", "received_at": "datetime", "context_source_id": "string", "context_request_ip": "string", "context_source_type": "string", "context_destination_id": "string", "context_traits_trait_1": "string", "context_destination_type": "string", "uuid_ts": "datetime", "loaded_at": "datetime"}, "receivedAt": "2023-05-09T21:24:14.846+05:30"}}`
	tracksTemplate       = `{"data": {"id": "{{.msgID}}", "event": "product_track", "sent_at": "2023-05-09T15:54:16.022Z", "user_id": "{{.userID}}", "timestamp": "2023-05-09T15:54:14.875Z", "context_ip": "[::1]", "event_text": "Product Track", "received_at": "2023-05-09T15:54:14.876Z", "context_source_id": "{{.sourceID}}", "context_request_ip": "[::1]", "original_timestamp": "2023-05-09T15:54:16.022Z", "context_source_type": "Javascript", "context_destination_id": "{{.destID}}", "context_destination_type": "{{.destType}}"}, "userId": "", "metadata": {"table": "tracks", "columns": {"id": "string", "event": "string", "sent_at": "datetime", "user_id": "string", "uuid_ts": "datetime", "timestamp": "datetime", "context_ip": "string", "event_text": "string", "received_at": "datetime", "context_source_id": "string", "context_request_ip": "string", "original_timestamp": "datetime", "context_source_type": "string", "context_destination_id": "string", "context_destination_type": "string", "uuid_ts": "datetime", "loaded_at": "datetime"}, "receivedAt": "2023-05-09T21:24:14.876+05:30"}}`
	productTrackTemplate = `{"data": {"id": "{{.msgID}}", "event": "product_track", "rating": 3, "sent_at": "2023-05-09T15:54:16.022Z", "user_id": "{{.userID}}", "review_id": "12345", "timestamp": "2023-05-09T15:54:14.875Z", "context_ip": "[::1]", "event_text": "Product Track", "product_id": "123", "received_at": "2023-05-09T15:54:14.876Z", "review_body": "Average product, expected much more.", "context_source_id": "{{.sourceID}}", "context_request_ip": "[::1]", "original_timestamp": "2023-05-09T15:54:16.022Z", "context_source_type": "Javascript", "context_destination_id": "{{.destID}}", "context_destination_type": "{{.destType}}"}, "userId": "", "metadata": {"table": "product_track", "columns": {"id": "string", "event": "string", "rating": "int", "sent_at": "datetime", "user_id": "string", "uuid_ts": "datetime", "review_id": "string", "timestamp": "datetime", "context_ip": "string", "event_text": "string", "product_id": "string", "received_at": "datetime", "review_body": "string", "context_source_id": "string", "context_request_ip": "string", "original_timestamp": "datetime", "context_source_type": "string", "context_destination_id": "string", "context_destination_type": "string", "uuid_ts": "datetime", "loaded_at": "datetime"}, "receivedAt": "2023-05-09T21:24:14.876+05:30"}}`
	pagesTemplate        = `{"data": {"id": "{{.msgID}}", "url": "https://www.rudderstack.com", "name": "Home", "title": "Home | RudderStack", "sent_at": "2023-05-09T15:54:16.022Z", "user_id": "{{.userID}}", "timestamp": "2023-05-09T15:54:14.906Z", "context_ip": "[::1]", "received_at": "2023-05-09T15:54:14.907Z", "context_source_id": "{{.sourceID}}", "context_request_ip": "[::1]", "original_timestamp": "2023-05-09T15:54:16.022Z", "context_source_type": "Javascript", "context_destination_id": "{{.destID}}", "context_destination_type": "{{.destType}}"}, "userId": "", "metadata": {"table": "pages", "columns": {"id": "string", "url": "string", "name": "string", "title": "string", "sent_at": "datetime", "user_id": "string", "uuid_ts": "datetime", "timestamp": "datetime", "context_ip": "string", "received_at": "datetime", "context_source_id": "string", "context_request_ip": "string", "original_timestamp": "datetime", "context_source_type": "string", "context_destination_id": "string", "context_destination_type": "string", "uuid_ts": "datetime", "loaded_at": "datetime"}, "receivedAt": "2023-05-09T21:24:14.907+05:30"}}`
	screensTemplate      = `{"data": {"id": "{{.msgID}}", "name": "Main", "sent_at": "2023-05-09T15:54:16.022Z", "user_id": "{{.userID}}", "prop_key": "prop_value", "timestamp": "2023-05-09T15:54:14.936Z", "context_ip": "[::1]", "received_at": "2023-05-09T15:54:14.937Z", "context_source_id": "{{.sourceID}}", "context_request_ip": "[::1]", "original_timestamp": "2023-05-09T15:54:16.022Z", "context_source_type": "Javascript", "context_destination_id": "{{.destID}}", "context_destination_type": "{{.destType}}"}, "userId": "", "metadata": {"table": "screens", "columns": {"id": "string", "name": "string", "sent_at": "datetime", "user_id": "string", "uuid_ts": "datetime", "prop_key": "string", "timestamp": "datetime", "context_ip": "string", "received_at": "datetime", "context_source_id": "string", "context_request_ip": "string", "original_timestamp": "datetime", "context_source_type": "string", "context_destination_id": "string", "context_destination_type": "string", "uuid_ts": "datetime", "loaded_at": "datetime"}, "receivedAt": "2023-05-09T21:24:14.937+05:30"}}`
	aliasesTemplate      = `{"data": {"id": "{{.msgID}}", "sent_at": "2023-05-09T15:54:16.022Z", "user_id": "{{.userID}}", "timestamp": "2023-05-09T15:54:14.951Z", "context_ip": "[::1]", "previous_id": "name@surname.com", "received_at": "2023-05-09T15:54:14.952Z", "context_source_id": "{{.sourceID}}", "context_request_ip": "[::1]", "original_timestamp": "2023-05-09T15:54:16.022Z", "context_source_type": "Javascript", "context_destination_id": "{{.destID}}", "context_destination_type": "{{.destType}}"}, "userId": "", "metadata": {"table": "aliases", "columns": {"id": "string", "sent_at": "datetime", "user_id": "string", "uuid_ts": "datetime", "timestamp": "datetime", "context_ip": "string", "previous_id": "string", "received_at": "datetime", "context_source_id": "string", "context_request_ip": "string", "original_timestamp": "datetime", "context_source_type": "string", "context_destination_id": "string", "context_destination_type": "string", "uuid_ts": "datetime", "loaded_at": "datetime"}, "receivedAt": "2023-05-09T21:24:14.952+05:30"}}`
	groupsTemplate       = `{"data": {"id": "{{.msgID}}", "name": "MyGroup", "_plan": "basic", "sent_at": "2023-05-09T15:54:16.022Z", "user_id": "{{.userID}}", "group_id": "groupId", "industry": "IT", "employees": 450, "timestamp": "2023-05-09T15:54:14.966Z", "context_ip": "[::1]", "received_at": "2023-05-09T15:54:14.967Z", "context_source_id": "{{.sourceID}}", "context_request_ip": "[::1]", "original_timestamp": "2023-05-09T15:54:16.022Z", "context_source_type": "Javascript", "context_destination_id": "{{.destID}}", "context_destination_type": "{{.destType}}"}, "userId": "", "metadata": {"table": "groups", "columns": {"id": "string", "name": "string", "_plan": "string", "sent_at": "datetime", "user_id": "string", "uuid_ts": "datetime", "group_id": "string", "industry": "string", "employees": "int", "timestamp": "datetime", "context_ip": "string", "received_at": "datetime", "context_source_id": "string", "context_request_ip": "string", "original_timestamp": "datetime", "context_source_type": "string", "context_destination_id": "string", "context_destination_type": "string", "uuid_ts": "datetime", "loaded_at": "datetime"}, "receivedAt": "2023-05-09T21:24:14.967+05:30"}}`

	identifiesModifiedTemplate   = `{"data": {"id": "{{.msgID}}", "sent_at": "2023-05-09T15:54:27.327Z", "trait_1": "new-val", "user_id": "{{.userID}}", "timestamp": "2020-02-02T00:23:09.544Z", "context_ip": "14.5.67.21", "received_at": "2023-05-09T15:54:26.839Z", "context_passed_ip": "14.5.67.21", "context_source_id": "{{.sourceID}}", "context_request_ip": "[::1]", "original_timestamp": "2023-05-09T15:54:27.327Z", "context_source_type": "Javascript", "context_library_name": "http", "context_destination_id": "{{.destID}}", "context_traits_trait_1": "new-val", "context_destination_type": "{{.destType}}"}, "userId": "", "metadata": {"table": "identifies", "columns": {"id": "string", "sent_at": "datetime", "trait_1": "string", "user_id": "string", "uuid_ts": "datetime", "timestamp": "datetime", "context_ip": "string", "received_at": "datetime", "context_passed_ip": "string", "context_source_id": "string", "context_request_ip": "string", "original_timestamp": "datetime", "context_source_type": "string", "context_library_name": "string", "context_destination_id": "string", "context_traits_trait_1": "string", "context_destination_type": "string", "uuid_ts": "datetime", "loaded_at": "datetime"}, "receivedAt": "2023-05-09T21:24:26.839+05:30"}}`
	usersModifiedTemplate        = `{"data": {"id": "{{.userID}}", "trait_1": "new-val", "context_ip": "14.5.67.21", "received_at": "2023-05-09T15:54:26.839Z", "context_passed_ip": "14.5.67.21", "context_source_id": "{{.sourceID}}", "context_request_ip": "[::1]", "context_source_type": "Javascript", "context_library_name": "http", "context_destination_id": "{{.destID}}", "context_traits_trait_1": "new-val", "context_destination_type": "{{.destType}}"}, "userId": "", "metadata": {"table": "users", "columns": {"id": "string", "trait_1": "string", "uuid_ts": "datetime", "context_ip": "string", "received_at": "datetime", "context_passed_ip": "string", "context_source_id": "string", "context_request_ip": "string", "context_source_type": "string", "context_library_name": "string", "context_destination_id": "string", "context_traits_trait_1": "string", "context_destination_type": "string", "uuid_ts": "datetime", "loaded_at": "datetime"}, "receivedAt": "2023-05-09T21:24:26.839+05:30"}}`
	tracksModifiedTemplate       = `{"data": {"id": "{{.msgID}}", "event": "product_track", "sent_at": "2023-05-09T15:54:27.327Z", "user_id": "{{.userID}}", "timestamp": "2023-05-09T15:54:26.865Z", "context_ip": "14.5.67.21", "event_text": "Product Track", "received_at": "2023-05-09T15:54:26.866Z", "context_passed_ip": "14.5.67.21", "context_source_id": "{{.sourceID}}", "context_request_ip": "[::1]", "original_timestamp": "2023-05-09T15:54:27.327Z", "context_source_type": "Javascript", "context_library_name": "http", "context_destination_id": "{{.destID}}", "context_destination_type": "{{.destType}}"}, "userId": "", "metadata": {"table": "tracks", "columns": {"id": "string", "event": "string", "sent_at": "datetime", "user_id": "string", "uuid_ts": "datetime", "timestamp": "datetime", "context_ip": "string", "event_text": "string", "received_at": "datetime", "context_passed_ip": "string", "context_source_id": "string", "context_request_ip": "string", "original_timestamp": "datetime", "context_source_type": "string", "context_library_name": "string", "context_destination_id": "string", "context_destination_type": "string", "uuid_ts": "datetime", "loaded_at": "datetime"}, "receivedAt": "2023-05-09T21:24:26.866+05:30"}}`
	productTrackModifiedTemplate = `{"data": {"id": "{{.msgID}}", "event": "product_track", "rating": 3, "revenue": 4.99, "sent_at": "2023-05-09T15:54:27.327Z", "user_id": "{{.userID}}", "review_id": "12345", "timestamp": "2023-05-09T15:54:26.865Z", "context_ip": "14.5.67.21", "event_text": "Product Track", "product_id": "123", "received_at": "2023-05-09T15:54:26.866Z", "review_body": "Average product, expected much more.", "context_passed_ip": "14.5.67.21", "context_source_id": "{{.sourceID}}", "context_request_ip": "[::1]", "original_timestamp": "2023-05-09T15:54:27.327Z", "context_source_type": "Javascript", "context_library_name": "http", "context_destination_id": "{{.destID}}", "context_destination_type": "{{.destType}}"}, "userId": "", "metadata": {"table": "product_track", "columns": {"id": "string", "event": "string", "rating": "int", "revenue": "float", "sent_at": "datetime", "user_id": "string", "uuid_ts": "datetime", "review_id": "string", "timestamp": "datetime", "context_ip": "string", "event_text": "string", "product_id": "string", "received_at": "datetime", "review_body": "string", "context_passed_ip": "string", "context_source_id": "string", "context_request_ip": "string", "original_timestamp": "datetime", "context_source_type": "string", "context_library_name": "string", "context_destination_id": "string", "context_destination_type": "string", "uuid_ts": "datetime", "loaded_at": "datetime"}, "receivedAt": "2023-05-09T21:24:26.866+05:30"}}`
	pagesModifiedTemplate        = `{"data": {"id": "{{.msgID}}", "url": "https://www.rudderstack.com", "name": "Home", "title": "Home | RudderStack", "sent_at": "2023-05-09T15:54:27.327Z", "user_id": "{{.userID}}", "timestamp": "2023-05-09T15:54:26.881Z", "context_ip": "14.5.67.21", "received_at": "2023-05-09T15:54:26.882Z", "context_passed_ip": "14.5.67.21", "context_source_id": "{{.sourceID}}", "context_request_ip": "[::1]", "original_timestamp": "2023-05-09T15:54:27.327Z", "context_source_type": "Javascript", "context_library_name": "http", "context_destination_id": "{{.destID}}", "context_destination_type": "{{.destType}}"}, "userId": "", "metadata": {"table": "pages", "columns": {"id": "string", "url": "string", "name": "string", "title": "string", "sent_at": "datetime", "user_id": "string", "uuid_ts": "datetime", "timestamp": "datetime", "context_ip": "string", "received_at": "datetime", "context_passed_ip": "string", "context_source_id": "string", "context_request_ip": "string", "original_timestamp": "datetime", "context_source_type": "string", "context_library_name": "string", "context_destination_id": "string", "context_destination_type": "string", "uuid_ts": "datetime", "loaded_at": "datetime"}, "receivedAt": "2023-05-09T21:24:26.882+05:30"}}`
	screensModifiedTemplate      = `{"data": {"id": "{{.msgID}}", "name": "Main", "sent_at": "2023-05-09T15:54:27.327Z", "user_id": "{{.userID}}", "prop_key": "prop_value", "timestamp": "2023-05-09T15:54:26.906Z", "context_ip": "14.5.67.21", "received_at": "2023-05-09T15:54:26.907Z", "context_passed_ip": "14.5.67.21", "context_source_id": "{{.sourceID}}", "context_request_ip": "[::1]", "original_timestamp": "2023-05-09T15:54:27.327Z", "context_source_type": "Javascript", "context_library_name": "http", "context_destination_id": "{{.destID}}", "context_destination_type": "{{.destType}}"}, "userId": "", "metadata": {"table": "screens", "columns": {"id": "string", "name": "string", "sent_at": "datetime", "user_id": "string", "uuid_ts": "datetime", "prop_key": "string", "timestamp": "datetime", "context_ip": "string", "received_at": "datetime", "context_passed_ip": "string", "context_source_id": "string", "context_request_ip": "string", "original_timestamp": "datetime", "context_source_type": "string", "context_library_name": "string", "context_destination_id": "string", "context_destination_type": "string", "uuid_ts": "datetime", "loaded_at": "datetime"}, "receivedAt": "2023-05-09T21:24:26.907+05:30"}}`
	aliasesModifiedTemplate      = `{"data": {"id": "{{.msgID}}", "sent_at": "2023-05-09T15:54:27.327Z", "user_id": "{{.userID}}", "timestamp": "2023-05-09T15:54:26.921Z", "context_ip": "14.5.67.21", "previous_id": "name@surname.com", "received_at": "2023-05-09T15:54:26.922Z", "context_passed_ip": "14.5.67.21", "context_source_id": "{{.sourceID}}", "context_request_ip": "[::1]", "original_timestamp": "2023-05-09T15:54:27.327Z", "context_source_type": "Javascript", "context_library_name": "http", "context_destination_id": "{{.destID}}", "context_destination_type": "{{.destType}}"}, "userId": "", "metadata": {"table": "aliases", "columns": {"id": "string", "sent_at": "datetime", "user_id": "string", "uuid_ts": "datetime", "timestamp": "datetime", "context_ip": "string", "previous_id": "string", "received_at": "datetime", "context_passed_ip": "string", "context_source_id": "string", "context_request_ip": "string", "original_timestamp": "datetime", "context_source_type": "string", "context_library_name": "string", "context_destination_id": "string", "context_destination_type": "string", "uuid_ts": "datetime", "loaded_at": "datetime"}, "receivedAt": "2023-05-09T21:24:26.922+05:30"}}`
	groupsModifiedTemplate       = `{"data": {"id": "{{.msgID}}", "name": "MyGroup", "_plan": "basic", "sent_at": "2023-05-09T15:54:27.327Z", "user_id": "{{.userID}}", "group_id": "groupId", "industry": "IT", "employees": 450, "timestamp": "2023-05-09T15:54:26.936Z", "context_ip": "14.5.67.21", "received_at": "2023-05-09T15:54:26.937Z", "context_passed_ip": "14.5.67.21", "context_source_id": "{{.sourceID}}", "context_request_ip": "[::1]", "original_timestamp": "2023-05-09T15:54:27.327Z", "context_source_type": "Javascript", "context_library_name": "http", "context_destination_id": "{{.destID}}", "context_destination_type": "{{.destType}}"}, "userId": "", "metadata": {"table": "groups", "columns": {"id": "string", "name": "string", "_plan": "string", "sent_at": "datetime", "user_id": "string", "uuid_ts": "datetime", "group_id": "string", "industry": "string", "employees": "int", "timestamp": "datetime", "context_ip": "string", "received_at": "datetime", "context_passed_ip": "string", "context_source_id": "string", "context_request_ip": "string", "original_timestamp": "datetime", "context_source_type": "string", "context_library_name": "string", "context_destination_id": "string", "context_destination_type": "string", "uuid_ts": "datetime", "loaded_at": "datetime"}, "receivedAt": "2023-05-09T21:24:26.937+05:30"}}`

	identifiesReservedTemplate   = `{"data": {"as": "non escaped column", "id": "{{.msgID}}", "between": "non escaped column", "sent_at": "2023-05-09T15:54:16.023Z", "trait_1": "new-val", "user_id": "{{.userID}}", "timestamp": "2020-02-02T00:23:09.544Z", "context_ip": "[::1]", "received_at": "2023-05-09T15:54:15.178Z", "context_source_id": "{{.sourceID}}", "context_traits_as": "non escaped column", "context_request_ip": "[::1]", "original_timestamp": "2023-05-09T15:54:16.023Z", "context_source_type": "Javascript", "context_destination_id": "{{.destID}}", "context_traits_between": "non escaped column", "context_traits_trait_1": "new-val", "context_destination_type": "{{.destType}}"}, "userId": "", "metadata": {"table": "identifies", "columns": {"as": "string", "id": "string", "between": "string", "sent_at": "datetime", "trait_1": "string", "user_id": "string", "uuid_ts": "datetime", "timestamp": "datetime", "context_ip": "string", "received_at": "datetime", "context_source_id": "string", "context_traits_as": "string", "context_request_ip": "string", "original_timestamp": "datetime", "context_source_type": "string", "context_destination_id": "string", "context_traits_between": "string", "context_traits_trait_1": "string", "context_destination_type": "string", "uuid_ts": "datetime", "loaded_at": "datetime"}, "receivedAt": "2023-05-09T21:24:15.178+05:30"}}`
	usersReservedTemplate        = `{"data": {"as": "non escaped column", "id": "{{.userID}}", "between": "non escaped column", "trait_1": "new-val", "context_ip": "[::1]", "received_at": "2023-05-09T15:54:15.178Z", "context_source_id": "{{.sourceID}}", "context_traits_as": "non escaped column", "context_request_ip": "[::1]", "context_source_type": "Javascript", "context_destination_id": "{{.destID}}", "context_traits_between": "non escaped column", "context_traits_trait_1": "new-val", "context_destination_type": "{{.destType}}"}, "userId": "", "metadata": {"table": "users", "columns": {"as": "string", "id": "string", "between": "string", "trait_1": "string", "uuid_ts": "datetime", "context_ip": "string", "received_at": "datetime", "context_source_id": "string", "context_traits_as": "string", "context_request_ip": "string", "context_source_type": "string", "context_destination_id": "string", "context_traits_between": "string", "context_traits_trait_1": "string", "context_destination_type": "string", "uuid_ts": "datetime", "loaded_at": "datetime"}, "receivedAt": "2023-05-09T21:24:15.178+05:30"}}`
	tracksReservedTemplate       = `{"data": {"as": "non escaped column", "id": "{{.msgID}}", "event": "product_track", "sent_at": "2023-05-09T15:54:16.023Z", "user_id": "{{.userID}}", "timestamp": "2023-05-09T15:54:15.192Z", "context_ip": "[::1]", "event_text": "Product Track", "received_at": "2023-05-09T15:54:15.193Z", "context_source_id": "{{.sourceID}}", "context_request_ip": "[::1]", "original_timestamp": "2023-05-09T15:54:16.023Z", "context_source_type": "Javascript", "context_destination_id": "{{.destID}}", "context_destination_type": "{{.destType}}"}, "userId": "", "metadata": {"table": "tracks", "columns": {"id": "string", "event": "string", "sent_at": "datetime", "user_id": "string", "uuid_ts": "datetime", "timestamp": "datetime", "context_ip": "string", "event_text": "string", "received_at": "datetime", "context_source_id": "string", "context_request_ip": "string", "original_timestamp": "datetime", "context_source_type": "string", "context_destination_id": "string", "context_destination_type": "string", "uuid_ts": "datetime", "loaded_at": "datetime"}, "receivedAt": "2023-05-09T21:24:15.193+05:30"}}`
	productTrackReservedTemplate = `{"data": {"as": "non escaped column", "id": "{{.msgID}}", "event": "product_track", "rating": 3, "between": "non escaped column", "sent_at": "2023-05-09T15:54:16.023Z", "user_id": "{{.userID}}", "review_id": "12345", "timestamp": "2023-05-09T15:54:15.192Z", "context_ip": "[::1]", "event_text": "Product Track", "product_id": "123", "received_at": "2023-05-09T15:54:15.193Z", "review_body": "Average product, expected much more.", "context_source_id": "{{.sourceID}}", "context_request_ip": "[::1]", "original_timestamp": "2023-05-09T15:54:16.023Z", "context_source_type": "Javascript", "context_destination_id": "{{.destID}}", "context_destination_type": "{{.destType}}"}, "userId": "", "metadata": {"table": "product_track", "columns": {"as": "string", "id": "string", "event": "string", "rating": "int", "between": "string", "sent_at": "datetime", "user_id": "string", "uuid_ts": "datetime", "review_id": "string", "timestamp": "datetime", "context_ip": "string", "event_text": "string", "product_id": "string", "received_at": "datetime", "review_body": "string", "context_source_id": "string", "context_request_ip": "string", "original_timestamp": "datetime", "context_source_type": "string", "context_destination_id": "string", "context_destination_type": "string", "uuid_ts": "datetime", "loaded_at": "datetime"}, "receivedAt": "2023-05-09T21:24:15.193+05:30"}}`
	pagesReservedTemplate        = `{"data": {"as": "non escaped column", "id": "{{.msgID}}", "url": "https://www.rudderstack.com", "name": "Home", "title": "Home | RudderStack", "between": "non escaped column", "sent_at": "2023-05-09T15:54:16.023Z", "user_id": "{{.userID}}", "timestamp": "2023-05-09T15:54:15.207Z", "context_ip": "[::1]", "received_at": "2023-05-09T15:54:15.208Z", "context_source_id": "{{.sourceID}}", "context_request_ip": "[::1]", "original_timestamp": "2023-05-09T15:54:16.023Z", "context_source_type": "Javascript", "context_destination_id": "{{.destID}}", "context_destination_type": "{{.destType}}"}, "userId": "", "metadata": {"table": "pages", "columns": {"as": "string", "id": "string", "url": "string", "name": "string", "title": "string", "between": "string", "sent_at": "datetime", "user_id": "string", "uuid_ts": "datetime", "timestamp": "datetime", "context_ip": "string", "received_at": "datetime", "context_source_id": "string", "context_request_ip": "string", "original_timestamp": "datetime", "context_source_type": "string", "context_destination_id": "string", "context_destination_type": "string", "uuid_ts": "datetime", "loaded_at": "datetime"}, "receivedAt": "2023-05-09T21:24:15.208+05:30"}}`
	screensReservedTemplate      = `{"data": {"as": "non escaped column", "id": "{{.msgID}}", "name": "Main", "between": "non escaped column", "sent_at": "2023-05-09T15:54:16.023Z", "user_id": "{{.userID}}", "prop_key": "prop_value", "timestamp": "2023-05-09T15:54:15.222Z", "context_ip": "[::1]", "received_at": "2023-05-09T15:54:15.223Z", "context_source_id": "{{.sourceID}}", "context_request_ip": "[::1]", "original_timestamp": "2023-05-09T15:54:16.023Z", "context_source_type": "Javascript", "context_destination_id": "{{.destID}}", "context_destination_type": "{{.destType}}"}, "userId": "", "metadata": {"table": "screens", "columns": {"as": "string", "id": "string", "name": "string", "between": "string", "sent_at": "datetime", "user_id": "string", "uuid_ts": "datetime", "prop_key": "string", "timestamp": "datetime", "context_ip": "string", "received_at": "datetime", "context_source_id": "string", "context_request_ip": "string", "original_timestamp": "datetime", "context_source_type": "string", "context_destination_id": "string", "context_destination_type": "string", "uuid_ts": "datetime", "loaded_at": "datetime"}, "receivedAt": "2023-05-09T21:24:15.223+05:30"}}`
	aliasesReservedTemplate      = `{"data": {"as": "non escaped column", "id": "{{.msgID}}", "sent_at": "2023-05-09T15:54:16.023Z", "user_id": "{{.userID}}", "timestamp": "2023-05-09T15:54:15.237Z", "context_ip": "[::1]", "previous_id": "name@surname.com", "received_at": "2023-05-09T15:54:15.238Z", "context_source_id": "{{.sourceID}}", "context_request_ip": "[::1]", "original_timestamp": "2023-05-09T15:54:16.023Z", "context_source_type": "Javascript", "context_destination_id": "{{.destID}}", "context_destination_type": "{{.destType}}"}, "userId": "", "metadata": {"table": "aliases", "columns": {"id": "string", "sent_at": "datetime", "user_id": "string", "uuid_ts": "datetime", "timestamp": "datetime", "context_ip": "string", "previous_id": "string", "received_at": "datetime", "context_source_id": "string", "context_request_ip": "string", "original_timestamp": "datetime", "context_source_type": "string", "context_destination_id": "string", "context_destination_type": "string", "uuid_ts": "datetime", "loaded_at": "datetime"}, "receivedAt": "2023-05-09T21:24:15.238+05:30"}}`
	groupsReservedTemplate       = `{"data": {"as": "non escaped column", "id": "{{.msgID}}", "name": "MyGroup", "plan": "basic", "between": "non escaped column", "sent_at": "2023-05-09T15:54:16.023Z", "user_id": "{{.userID}}", "group_id": "groupId", "industry": "IT", "employees": 450, "timestamp": "2023-05-09T15:54:15.252Z", "context_ip": "[::1]", "received_at": "2023-05-09T15:54:15.253Z", "context_source_id": "{{.sourceID}}", "context_request_ip": "[::1]", "original_timestamp": "2023-05-09T15:54:16.023Z", "context_source_type": "Javascript", "context_destination_id": "{{.destID}}", "context_destination_type": "{{.destType}}"}, "userId": "", "metadata": {"table": "groups", "columns": {"as": "string", "id": "string", "name": "string", "plan": "string", "between": "string", "sent_at": "datetime", "user_id": "string", "uuid_ts": "datetime", "group_id": "string", "industry": "string", "employees": "int", "timestamp": "datetime", "context_ip": "string", "received_at": "datetime", "context_source_id": "string", "context_request_ip": "string", "original_timestamp": "datetime", "context_source_type": "string", "context_destination_id": "string", "context_destination_type": "string", "uuid_ts": "datetime", "loaded_at": "datetime"}, "receivedAt": "2023-05-09T21:24:15.253+05:30"}}`

	googleSheetTemplate              = `{"data": {"id": "{{.msgID}}", "event": "google_sheet", "header": "HBD5", "channel": "sources", "sent_at": "2023-05-10T19:42:38.957Z", "user_id": "{{.userID}}", "header_4": "esgseg78", "timestamp": "2023-05-10T19:42:38.429Z", "context_ip": "[::1]", "event_text": "google_sheet", "received_at": "2023-05-10T19:42:38.430Z", "context_source_id": "{{.sourceID}}", "context_request_ip": "[::1]", "original_timestamp": "2023-05-10T19:42:38.957Z", "context_source_type": "singer-google-sheets", "context_destination_id": "{{.destID}}", "context_sources_job_id": "2DkCpUr0xfiGBPJxIwqyqfyHdq4", "context_sources_task_id": "Sheet1", "context_sources_version": "v2.1.1", "context_destination_type": "{{.destType}}", "context_sources_batch_id": "e84d84e1-be39-41cb-85e6-66874b6a4730", "context_sources_job_run_id": "{{.jobRunID}}", "context_sources_task_run_id": "{{.taskRunID}}"}, "userId": "", "metadata": {"table": "google_sheet", "columns": {"id": "string", "event": "string", "header": "string", "channel": "string", "sent_at": "datetime", "user_id": "string", "uuid_ts": "datetime", "header_4": "string", "timestamp": "datetime", "context_ip": "string", "event_text": "string", "received_at": "datetime", "context_source_id": "string", "context_request_ip": "string", "original_timestamp": "datetime", "context_source_type": "string", "context_destination_id": "string", "context_sources_job_id": "string", "context_sources_task_id": "string", "context_sources_version": "string", "context_destination_type": "string", "context_sources_batch_id": "string", "context_sources_job_run_id": "string", "context_sources_task_run_id": "string", "uuid_ts": "datetime", "loaded_at": "datetime"}, "receivedAt": "2023-05-11T01:12:38.430+05:30"}}`
	googleSheetModifiedTemplate      = `{"data": {"id": "{{.msgID}}", "event": "google_sheet", "header": "HBD5", "channel": "sources", "sent_at": "2023-05-10T19:42:56.270Z", "user_id": "{{.userID}}", "header_4": "esgseg78", "timestamp": "2023-05-10T19:42:54.635Z", "context_ip": "14.5.67.21", "event_text": "google_sheet", "received_at": "2023-05-10T19:42:54.636Z", "context_passed_ip": "14.5.67.21", "context_source_id": "{{.sourceID}}", "context_request_ip": "[::1]", "original_timestamp": "2023-05-10T19:42:56.270Z", "context_source_type": "singer-google-sheets", "context_library_name": "http", "context_destination_id": "{{.destID}}", "context_sources_job_id": "2DkCpUr0xfiGBPJxIwqyqfyHdq4", "context_sources_task_id": "Sheet1", "context_sources_version": "v2.1.1", "context_destination_type": "{{.destType}}", "context_sources_batch_id": "e84d84e1-be39-41cb-85e6-66874b6a4730", "context_sources_job_run_id": "{{.jobRunID}}", "context_sources_task_run_id": "{{.taskRunID}}"}, "userId": "", "metadata": {"table": "google_sheet", "columns": {"id": "string", "event": "string", "header": "string", "channel": "string", "sent_at": "datetime", "user_id": "string", "uuid_ts": "datetime", "header_4": "string", "timestamp": "datetime", "context_ip": "string", "event_text": "string", "received_at": "datetime", "context_passed_ip": "string", "context_source_id": "string", "context_request_ip": "string", "original_timestamp": "datetime", "context_source_type": "string", "context_library_name": "string", "context_destination_id": "string", "context_sources_job_id": "string", "context_sources_task_id": "string", "context_sources_version": "string", "context_destination_type": "string", "context_sources_batch_id": "string", "context_sources_job_run_id": "string", "context_sources_task_run_id": "string", "uuid_ts": "datetime", "loaded_at": "datetime"}, "receivedAt": "2023-05-11T01:12:54.636+05:30"}}`
	googleSheetReservedTemplate      = `{"data": {"as": "non escaped column", "id": "{{.msgID}}", "event": "google_sheet", "between": "non escaped column", "channel": "sources", "sent_at": "2023-05-10T19:42:38.958Z", "user_id": "{{.userID}}", "prop_key": "prop_value", "timestamp": "2023-05-10T19:42:38.519Z", "context_as": "non escaped column", "context_ip": "[::1]", "event_text": "google_sheet", "received_at": "2023-05-10T19:42:38.520Z", "context_between": "non escaped column", "context_source_id": "{{.sourceID}}", "context_request_ip": "[::1]", "original_timestamp": "2023-05-10T19:42:38.958Z", "context_source_type": "singer-google-sheets", "context_destination_id": "{{.destID}}", "context_sources_job_id": "2DkCpUr0xfiGBPJxIwqyqfyHdq4", "context_sources_task_id": "Sheet1", "context_sources_version": "v2.1.1", "context_destination_type": "{{.destType}}", "context_sources_batch_id": "e84d84e1-be39-41cb-85e6-66874b6a4730", "context_sources_job_run_id": "{{.jobRunID}}", "context_sources_task_run_id": "{{.taskRunID}}"}, "userId": "", "metadata": {"table": "google_sheet", "columns": {"as": "string", "id": "string", "event": "string", "between": "string", "channel": "string", "sent_at": "datetime", "user_id": "string", "uuid_ts": "datetime", "prop_key": "string", "timestamp": "datetime", "context_as": "string", "context_ip": "string", "event_text": "string", "received_at": "datetime", "context_between": "string", "context_source_id": "string", "context_request_ip": "string", "original_timestamp": "datetime", "context_source_type": "string", "context_destination_id": "string", "context_sources_job_id": "string", "context_sources_task_id": "string", "context_sources_version": "string", "context_destination_type": "string", "context_sources_batch_id": "string", "context_sources_job_run_id": "string", "context_sources_task_run_id": "string", "uuid_ts": "datetime", "loaded_at": "datetime"}, "receivedAt": "2023-05-11T01:12:38.520+05:30"}}`
	googleSheetTrackTemplate         = `{"data": {"id": "{{.msgID}}", "event": "google_sheet", "channel": "sources", "sent_at": "2023-05-10T19:42:38.957Z", "user_id": "{{.userID}}", "record_id": "{{.recordID}}", "timestamp": "2023-05-10T19:42:38.429Z", "context_ip": "[::1]", "event_text": "google_sheet", "received_at": "2023-05-10T19:42:38.430Z", "context_source_id": "{{.sourceID}}", "context_request_ip": "[::1]", "original_timestamp": "2023-05-10T19:42:38.957Z", "context_source_type": "singer-google-sheets", "context_destination_id": "{{.destID}}", "context_sources_job_id": "{{.jobRunID}}", "context_sources_task_id": "Sheet1", "context_sources_version": "v2.1.1", "context_destination_type": "{{.destType}}", "context_sources_batch_id": "e84d84e1-be39-41cb-85e6-66874b6a4730", "context_sources_job_run_id": "{{.jobRunID}}", "context_sources_task_run_id": "{{.taskRunID}}"}, "userId": "", "metadata": {"table": "tracks", "columns": {"id": "string", "event": "string", "channel": "string", "sent_at": "datetime", "user_id": "string", "uuid_ts": "datetime", "record_id": "string", "timestamp": "datetime", "context_ip": "string", "event_text": "string", "received_at": "datetime", "context_source_id": "string", "context_request_ip": "string", "original_timestamp": "datetime", "context_source_type": "string", "context_destination_id": "string", "context_sources_job_id": "string", "context_sources_task_id": "string", "context_sources_version": "string", "context_destination_type": "string", "context_sources_batch_id": "string", "context_sources_job_run_id": "string", "context_sources_task_run_id": "string", "uuid_ts": "datetime", "loaded_at": "datetime"}, "receivedAt": "2023-05-11T01:12:38.430+05:30"}}`
	googleSheetTrackModifiedTemplate = `{"data": {"id": "{{.msgID}}", "event": "google_sheet", "channel": "sources", "sent_at": "2023-05-10T19:42:38.958Z", "user_id": "{{.userID}}", "record_id": "{{.recordID}}", "timestamp": "2023-05-10T19:42:38.519Z", "context_as": "non escaped column", "context_ip": "[::1]", "event_text": "google_sheet", "received_at": "2023-05-10T19:42:38.520Z", "context_between": "non escaped column", "context_source_id": "{{.sourceID}}", "context_request_ip": "[::1]", "original_timestamp": "2023-05-10T19:42:38.958Z", "context_source_type": "singer-google-sheets", "context_destination_id": "{{.destID}}", "context_sources_job_id": "{{.jobRunID}}", "context_sources_task_id": "Sheet1", "context_sources_version": "v2.1.1", "context_destination_type": "{{.destType}}", "context_sources_batch_id": "e84d84e1-be39-41cb-85e6-66874b6a4730", "context_sources_job_run_id": "{{.jobRunID}}", "context_sources_task_run_id": "{{.taskRunID}}"}, "userId": "", "metadata": {"table": "tracks", "columns": {"id": "string", "event": "string", "channel": "string", "sent_at": "datetime", "user_id": "string", "uuid_ts": "datetime", "record_id": "string", "timestamp": "datetime", "context_as": "string", "context_ip": "string", "event_text": "string", "received_at": "datetime", "context_between": "string", "context_source_id": "string", "context_request_ip": "string", "original_timestamp": "datetime", "context_source_type": "string", "context_destination_id": "string", "context_sources_job_id": "string", "context_sources_task_id": "string", "context_sources_version": "string", "context_destination_type": "string", "context_sources_batch_id": "string", "context_sources_job_run_id": "string", "context_sources_task_run_id": "string", "uuid_ts": "datetime", "loaded_at": "datetime"}, "receivedAt": "2023-05-11T01:12:38.520+05:30"}}`
	googleSheetTrackReservedTemplate = `{"data": {"as": "non escaped column", "id": "{{.msgID}}", "event": "google_sheet", "channel": "sources", "sent_at": "2023-05-10T19:42:56.270Z", "user_id": "{{.userID}}", "record_id": "{{.recordID}}", "timestamp": "2023-05-10T19:42:54.701Z", "context_as": "non escaped column", "context_ip": "[::1]", "event_text": "google_sheet", "received_at": "2023-05-10T19:42:54.702Z", "context_between": "non escaped column", "context_source_id": "{{.sourceID}}", "context_request_ip": "[::1]", "original_timestamp": "2023-05-10T19:42:56.270Z", "context_source_type": "singer-google-sheets", "context_destination_id": "{{.destID}}", "context_sources_job_id": "2DkCpUr0xfiGBPJxIwqyqfyHdq4", "context_sources_task_id": "Sheet1", "context_sources_version": "v2.1.1", "context_destination_type": "{{.destType}}", "context_sources_batch_id": "e84d84e1-be39-41cb-85e6-66874b6a4730", "context_sources_job_run_id": "{{.jobRunID}}", "context_sources_task_run_id": "{{.taskRunID}}"}, "userId": "", "metadata": {"table": "tracks", "columns": {"id": "string", "event": "string", "channel": "string", "sent_at": "datetime", "user_id": "string", "uuid_ts": "datetime", "record_id": "string", "timestamp": "datetime", "context_as": "string", "context_ip": "string", "event_text": "string", "received_at": "datetime", "context_between": "string", "context_source_id": "string", "context_request_ip": "string", "original_timestamp": "datetime", "context_source_type": "string", "context_destination_id": "string", "context_sources_job_id": "string", "context_sources_task_id": "string", "context_sources_version": "string", "context_destination_type": "string", "context_sources_batch_id": "string", "context_sources_job_run_id": "string", "context_sources_task_run_id": "string", "uuid_ts": "datetime", "loaded_at": "datetime"}, "receivedAt": "2023-05-11T01:12:54.702+05:30"}}`

	idResolutionTemplate = `{"data": {"MERGE_PROPERTY_1_TYPE": "user_id", "MERGE_PROPERTY_2_TYPE": "user_id", "MERGE_PROPERTY_1_VALUE": "{{.userID}}", "MERGE_PROPERTY_2_VALUE": "name@surname.com"}, "userId": "", "metadata": {"table": "RUDDER_IDENTITY_MERGE_RULES", "columns": {"MERGE_PROPERTY_1_TYPE": "string", "MERGE_PROPERTY_2_TYPE": "string", "MERGE_PROPERTY_1_VALUE": "string", "MERGE_PROPERTY_2_VALUE": "string"}, "receivedAt": "2023-05-11T11:48:06.177+05:30", "isMergeRule": true, "mergePropOne": "{{.userID}}", "mergePropTwo": "name@surname.com"}}`
)

var templatesMap = map[string]string{
	"identifiesTemplate":   identifiesTemplate,
	"usersTemplate":        usersTemplate,
	"tracksTemplate":       tracksTemplate,
	"productTrackTemplate": productTrackTemplate,
	"pagesTemplate":        pagesTemplate,
	"screensTemplate":      screensTemplate,
	"aliasesTemplate":      aliasesTemplate,
	"groupsTemplate":       groupsTemplate,

	"identifiesModifiedTemplate":   identifiesModifiedTemplate,
	"usersModifiedTemplate":        usersModifiedTemplate,
	"tracksModifiedTemplate":       tracksModifiedTemplate,
	"productTrackModifiedTemplate": productTrackModifiedTemplate,
	"pagesModifiedTemplate":        pagesModifiedTemplate,
	"screensModifiedTemplate":      screensModifiedTemplate,
	"aliasesModifiedTemplate":      aliasesModifiedTemplate,
	"groupsModifiedTemplate":       groupsModifiedTemplate,

	"identifiesReservedTemplate":   identifiesReservedTemplate,
	"usersReservedTemplate":        usersReservedTemplate,
	"tracksReservedTemplate":       tracksReservedTemplate,
	"productTrackReservedTemplate": productTrackReservedTemplate,
	"pagesReservedTemplate":        pagesReservedTemplate,
	"screensReservedTemplate":      screensReservedTemplate,
	"aliasesReservedTemplate":      aliasesReservedTemplate,
	"groupsReservedTemplate":       groupsReservedTemplate,

	"googleSheetTemplate":              googleSheetTemplate,
	"googleSheetModifiedTemplate":      googleSheetModifiedTemplate,
	"googleSheetReservedTemplate":      googleSheetReservedTemplate,
	"googleSheetTrackTemplate":         googleSheetTrackTemplate,
	"googleSheetTrackModifiedTemplate": googleSheetTrackModifiedTemplate,
	"googleSheetTrackReservedTemplate": googleSheetTrackReservedTemplate,

	"idResolutionTemplate": idResolutionTemplate,
}

func DefaultEventsCountMap() EventsCountMap {
	return EventsCountMap{
		"identifiesTemplate":           3,
		"usersTemplate":                3,
		"tracksTemplate":               3,
		"productTrackTemplate":         3,
		"pagesTemplate":                3,
		"screensTemplate":              3,
		"aliasesTemplate":              3,
		"groupsTemplate":               3,
		"identifiesReservedTemplate":   1,
		"usersReservedTemplate":        1,
		"tracksReservedTemplate":       1,
		"productTrackReservedTemplate": 1,
		"pagesReservedTemplate":        1,
		"screensReservedTemplate":      1,
		"aliasesReservedTemplate":      1,
		"groupsReservedTemplate":       1,
	}
}

func DefaultEventsCountMapWithIdResolution() EventsCountMap {
	def := DefaultEventsCountMap()
	def["idResolutionTemplate"] = 2
	return def
}

func ModifiedEventsCountMap() EventsCountMap {
	return EventsCountMap{
		"identifiesModifiedTemplate":   3,
		"usersModifiedTemplate":        3,
		"tracksModifiedTemplate":       3,
		"productTrackModifiedTemplate": 3,
		"pagesModifiedTemplate":        3,
		"screensModifiedTemplate":      3,
		"aliasesModifiedTemplate":      3,
		"groupsModifiedTemplate":       3,
		"identifiesReservedTemplate":   1,
		"usersReservedTemplate":        1,
		"tracksReservedTemplate":       1,
		"productTrackReservedTemplate": 1,
		"pagesReservedTemplate":        1,
		"screensReservedTemplate":      1,
		"aliasesReservedTemplate":      1,
		"groupsReservedTemplate":       1,
	}
}

func ModifiedEventsCountMapWithIdResolution() EventsCountMap {
	def := ModifiedEventsCountMap()
	def["idResolutionTemplate"] = 2
	return def
}

func DefaultSourcesEventsCountMap() EventsCountMap {
	return EventsCountMap{
		"googleSheetTemplate":              3,
		"googleSheetTrackTemplate":         3,
		"googleSheetReservedTemplate":      1,
		"googleSheetTrackReservedTemplate": 1,
	}
}

func DefaultSourcesEventsCountMapWithIDResolution() EventsCountMap {
	def := DefaultSourcesEventsCountMap()
	def["idResolutionTemplate"] = 1
	return def
}

func DefaultSourcesModifiedEventsCountMap() EventsCountMap {
	return EventsCountMap{
		"googleSheetModifiedTemplate":      3,
		"googleSheetTrackModifiedTemplate": 3,
		"googleSheetReservedTemplate":      1,
		"googleSheetTrackReservedTemplate": 1,
	}
}

func DefaultSourcesModifiedEventsCountMapWithIDResolution() EventsCountMap {
	def := DefaultSourcesModifiedEventsCountMap()
	def["idResolutionTemplate"] = 1
	return def
}
