// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/warehouse/validations (interfaces: Validator)

// Package mock_validator is a generated GoMock package.
package mock_validator

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	backendconfig "github.com/rudderlabs/rudder-server/backend-config"
	model "github.com/rudderlabs/rudder-server/warehouse/internal/model"
)

// MockValidator is a mock of Validator interface.
type MockValidator struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorMockRecorder
}

// MockValidatorMockRecorder is the mock recorder for MockValidator.
type MockValidatorMockRecorder struct {
	mock *MockValidator
}

// NewMockValidator creates a new mock instance.
func NewMockValidator(ctrl *gomock.Controller) *MockValidator {
	mock := &MockValidator{ctrl: ctrl}
	mock.recorder = &MockValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidator) EXPECT() *MockValidatorMockRecorder {
	return m.recorder
}

// CreateTempLoadFile mocks base method.
func (m *MockValidator) CreateTempLoadFile(arg0 *backendconfig.DestinationT) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTempLoadFile", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTempLoadFile indicates an expected call of CreateTempLoadFile.
func (mr *MockValidatorMockRecorder) CreateTempLoadFile(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTempLoadFile", reflect.TypeOf((*MockValidator)(nil).CreateTempLoadFile), arg0)
}

// Steps mocks base method.
func (m *MockValidator) Steps(arg0 *backendconfig.DestinationT) *model.StepsResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Steps", arg0)
	ret0, _ := ret[0].(*model.StepsResponse)
	return ret0
}

// Steps indicates an expected call of Steps.
func (mr *MockValidatorMockRecorder) Steps(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Steps", reflect.TypeOf((*MockValidator)(nil).Steps), arg0)
}

// Validate mocks base method.
func (m *MockValidator) Validate(arg0 context.Context, arg1 *backendconfig.DestinationT, arg2 string) *model.DestinationValidationResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", arg0, arg1, arg2)
	ret0, _ := ret[0].(*model.DestinationValidationResponse)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockValidatorMockRecorder) Validate(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockValidator)(nil).Validate), arg0, arg1, arg2)
}
