#!/bin/sh
# generates the imports/enterprise.go file, required to initialize enterprise features in rudder-server enterprise edition

GO=go

cat << EOF
// DO NOT EDIT - THIS FILE IS AUTOMATICALLY GENERATED BY enterprise/import.sh
package imports

import (
EOF

for p in `$GO list $1/...`; do
    echo "\t// load enterprise package"
    echo "\t_ \"$p\""
done
echo ")"


