// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/services/dedup (interfaces: Dedup)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/services/dedup/mock_dedup.go -package mock_dedup github.com/rudderlabs/rudder-server/services/dedup Dedup
//

// Package mock_dedup is a generated GoMock package.
package mock_dedup

import (
	reflect "reflect"

	types "github.com/rudderlabs/rudder-server/services/dedup/types"
	gomock "go.uber.org/mock/gomock"
)

// MockDedup is a mock of Dedup interface.
type MockDedup struct {
	ctrl     *gomock.Controller
	recorder *MockDedupMockRecorder
	isgomock struct{}
}

// MockDedupMockRecorder is the mock recorder for MockDedup.
type MockDedupMockRecorder struct {
	mock *MockDedup
}

// NewMockDedup creates a new mock instance.
func NewMockDedup(ctrl *gomock.Controller) *MockDedup {
	mock := &MockDedup{ctrl: ctrl}
	mock.recorder = &MockDedupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDedup) EXPECT() *MockDedupMockRecorder {
	return m.recorder
}

// Allowed mocks base method.
func (m *MockDedup) Allowed(keys ...types.BatchKey) (map[types.BatchKey]bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range keys {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Allowed", varargs...)
	ret0, _ := ret[0].(map[types.BatchKey]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Allowed indicates an expected call of Allowed.
func (mr *MockDedupMockRecorder) Allowed(keys ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allowed", reflect.TypeOf((*MockDedup)(nil).Allowed), keys...)
}

// Close mocks base method.
func (m *MockDedup) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockDedupMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDedup)(nil).Close))
}

// Commit mocks base method.
func (m *MockDedup) Commit(keys []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", keys)
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockDedupMockRecorder) Commit(keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockDedup)(nil).Commit), keys)
}
