name: Dispatch deploy event

on: workflow_dispatch

permissions:
  contents: read # Required for basic repository access

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - name: Create app token for cross-repo dispatch
        id: app-dispatch-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          app-id: ${{ vars.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_PRIVATE_KEY }}
          permission-contents: write
          repositories: rudder-devops

      - name: Repository dispatch
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3.0.0
        with:
          token: ${{ steps.app-dispatch-token.outputs.token }}
          repository: rudderlabs/rudder-devops
          event-type: deploy-event
          client-payload: |
            {
              "repo": "${{ github.repository }}",
              "commit-sha": "${{ github.sha }}",
              "images": {
                "server": {
                  "tag": "${{ github.ref_name }}"
                },
                "gateway": {
                  "tag": "${{ github.ref_name }}"
                },
                "warehouse-master": {
                  "tag": "${{ github.ref_name }}"
                },
                "warehouse-slave": {
                  "tag": "${{ github.ref_name }}"
                }
              },
              "value-paths": []
            }
