name: Handle stale PRs

on:
  schedule:
    - cron: '42 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - uses: actions/stale@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: 'This PR is considered to be stale. It has been open 20 days with no further activity thus it is going to be closed in 5 days. To avoid such a case please consider removing the stale label manually or add a comment to the PR.'
          days-before-pr-stale: 20
          days-before-pr-close: 7
          stale-pr-label: 'Stale'

