name: 'Pull Request Description'
on:
  pull_request:

permissions:
  pull-requests: read

jobs:
  enforce:
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - uses: rudderlabs/pr-description-enforcer@1354172a4395fcfaa645b59cf8ef3cefa19e4f6d # v1.1.0
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          placeholder-regex: '< Replace .* >'
