name: 'Pull Request Description'
on:
  pull_request:

permissions:
  pull-requests: read

jobs:
  enforce:
    runs-on: ubuntu-latest

    steps:
      - uses: rudderlabs/pr-description-enforcer@v1.1.0
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          placeholder-regex: '< Replace .* >'
