name: 'Pull Request Description'
on:
  pull_request:

permissions:
  pull-requests: read

jobs:
  enforce:
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - uses: rudderlabs/pr-description-enforcer@1354172a4395fcfaa645b59cf8ef3cefa19e4f6d # v1.1.0
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          placeholder-regex: '< Replace .* >'
